### PR TITLE
Prevent readdir of files by using getPackagesPaths

### LINKED ISSUE #4972: "yarn cache list" tries to readdir files
**Bug**
Running `yarn cache list` throws an error when no `.yarn-metadata` exists in some cached package that is in use by the current project

**To reproduce**
1. Get cache dir location
2. Remove `.yarn-metadata` from one of repos in the cache dir
3. run `yarn cache list`
4. Observer the error, e.g.: 
```
error An unexpected error occurred: "ENOTDIR: not a directory, scandir '/Users/agoldis/Library/Caches/Yarn/v1/npm-get-uri-2.0.1-dbdcacacd8c608a38316869368117697a1631c59/History.md'".
```
**What is the expected behavior?**
To skip / invalidate corrupted cached module

**Please mention your node.js, yarn and operating system version.**
MacOS High Sierra
Yarn 1.3.2
Node 8.9.0

### PR DESCRIPTION
**Pull request by agoldis**
Resolves #4972 

**Summary**
#4972 occurs when a cached package has no `.yarn-metadata.json` for some reason - that causes the code to consider the corrupted package as scoped and it tries to read subdirectories recursively.

The PR introduces new method `getPackagesPaths` that is used in both `clean` and `list` commands - that prevents exception that is thrown by the replaced code by verifying the current path is indeed a directory.

It also makes a better (I hope 😄 ) composition of the functions by preventing code duplication

**Test plan**
`yarn run test-only` run tests for listing cached packages, removing all packages, removing a specific package by name

### CODE REVIEW

**Comment by agoldis** [comment]
@kaylieEB I know you guys are busy, but any chance the PR can get some attention :)
I have been keeping this PR in sync with master. Thank you!

**Comment by arcanis** [comment]
Thanks a lot @agoldis ! I'd love to merge this PR, but do you mind writing an automated test in the __tests__ directory so that we can be sure that we never regress? That would be super helpful!

**Comment by agoldis** [comment]
@arcanis, thanks for reviewing the PR. I am currently relocating and quite busy witg arrangements. Will take care of test in a week or two.

**Comment by arcanis** [comment]
No problem, ping me when you need me :)

**Comment by agoldis** [comment]
@arcanis Back to business :) Please take a look at the tests added.
I have added a fixtures at `__tests__/fixtures/cache` with pre-populated bad cached packages.
The tests check they are ignored when listing.

**Comment by arcanis** [comment]
I'm sorry but we recently merged a PR that changed a bit how works the clean command (it now works with more than one package), and it conflicts with your diff ... I tried to resolve it myself through Github but the `getPackagesPaths` needs to be updated as well to accept a package name as parameter. Do you mind making the change? You might need to revert the commit I made.

Sorry I didn't get around merging this sooner.

**Comment by agoldis** [comment]
I will take care of that during the weekend 😉

**Comment by agoldis** [comment]
@arcanis fixed the merge. The changes:
- created `_getMetadataWithPath` that adds `path` to packages returned by `getCachedPackages`; the path is used to `fs.unlink` cached packages directories
- moved `clean` to be a distinct function
- using `getCachedPackages` in `clean` in the manner similar to `list`

**Comment by agoldis** [comment]
@arcanis I afraid it will become stale again :)

**Comment by arcanis** [comment]
LGTM! Thanks for the ping! 😃

**Pull request merged**
