### PR TITLE
Fixes to PR 6007

### LINKED ISSUE #6174: 1.9.2: Scoped Registries are being ignored
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

EDIT: This seems limited to `yarn global ...`

Since a recent (via my distro) update to `yarn 1.9.2`, scoped registry config set in `.yarnrc` or `.npmrc` are no longer being respected/used.
  
**If the current behavior is a bug, please provide the steps to reproduce.**
1) Use `config set` to set a scoped registry by running either one of the following:
```bash
$ npm config set @myscope:registry http://my.private.registry.com
# or
$ yarn config set @myscope:registry http://my.private.registry.com
```
2) Try adding a package from your scoped registry:
```bash
$ yarn global add @myscope/my-private-package
```
3) You'll get an error message that says:
`error An unexpected error occurred: "https://registry.yarnpkg.com/@myscope%2fmy-private-package: Not found".`

**What is the expected behavior?**

It should install the package from your private registry set for the scoped package.  In this example it should use `http://my.private.registry.com` not `https://registry.yarnpkg.com`.

**Please mention your node.js, yarn and operating system version.**

node: 10.7.0
yarn: 1.9.2
Elementary OS Loki (Ubuntu 16.04)

### PR DESCRIPTION
**Pull request by clintwood**
**Summary**

As a result of changes introduced in PR #6007 this PR resolves #6174 and provides a different implementation to #6181.

**Test plan**

All existing tests pass, PR #6007 added a number of tests but it seems the case of `yarn global ...` with scoped registries was not tested.  I cannot identify exactly how or where these tests should be done.  I'd be happy to do them if I'm pointed in the right direction.

### CODE REVIEW

**Comment by arcanis** [comment]
Thanks! I think testing this would imply:

- create a new fixture in `__tests__/fixtures/global/` that would contain a yarnrc and an empty pkg.json
- add a test in `__tests__/commands/global.js` that would run `yarn global add` with a scoped package
- check that it works as expected (not sure exactly how to do this part, I guess you can try setting an invalid registry for the scope and expect for the install to fail?)

**Comment by clintwood** [comment]
@arcanis, I have the basis of a test but cannot figure out how to generate and populate `./__tests__/fixtures/request-cache/GET/test-scope-registry.com/...` with the cache responses to my test scoped domain.  Some guidance from other contributors on how to do this would be appreciated!

**Comment by clintwood** [comment]
@arcanis - I've added a test for `yarn global add @test-scope/scoped-module` in
`__tests__/commands/global.js` with supporting fixtures
`__tests__/fixtures/global/add-with-scoped-registry` and
`__tests__/fixtures/request-cache/GET/test-scope-registry.com`.

I think this concludes the PR.

**Comment by arcanis** [comment]
Perfect, thanks!

**Pull request merged**
