### PR TITLE
Add pre and post install script calls

### LINKED ISSUE #783: Wrong script runed after install
**Do you want to request a *feature* or report a *bug*?**

Should be a bug.

**What is the current behavior?**

`propublish` script is runned after I use yarn

screen shot 2016-10-12 at 9 41 56 am

This is scripts part of my `package.json`:
``` json
  "scripts": {
    "postinstall": "webpack",
    "prepublish": "webpack --config webpack.prod.js"
  },
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn` command

**What is the expected behavior?**

It should run postinstall script.

**Please mention your node.js, yarn and operating system version.**

node v6.0
MacOs
yarn 0.15.1

### PR DESCRIPTION
**Pull request by FLGMwt**
**Summary**
Adds calls to the following named scripts: `preinstall`, `install`, `postinstall` and wraps `prepublish` in an `if !prod`, as it is in `npm install` Should resolve #783 Happy to discuss.

**Test plan**
Given the following package.json:
```
{
  "name": "junk",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "preinstall": "echo 'preinstall'",
    "install": "echo 'install'",
    "postinstall": "echo 'postinstall'",
    "prepublish": "echo 'prepublish'"
  }
}
```
`npm install` outputs the following:
```
PS C:\git\junk> npm i

> junk@1.0.0 preinstall C:\git\junk
> echo 'preinstall'

'preinstall'

> junk@1.0.0 install C:\git\junk
> echo 'install'

'install'

> junk@1.0.0 postinstall C:\git\junk
> echo 'postinstall'

'postinstall'

> junk@1.0.0 prepublish C:\git\junk
> echo 'prepublish'

'prepublish'
npm WARN junk@1.0.0 No description
npm WARN junk@1.0.0 No repository field.
```
`yarn`, however only executes `prepublish` (before changes):
```
PS C:\git\junk> yarn
yarn install v0.15.1
info No lockfile found.
success Nothing to install.
$ echo 'prepublish'
'prepublish'
Done in 0.06s.
```

After changes:
```
PS C:\git\junk> yarn
yarn install v0.15.1
info No lockfile found.
$ echo 'preinstall'
'preinstall'
success Nothing to install.
$ echo 'install'
'install'
$ echo 'postinstall'
'postinstall'
$ echo 'prepublish'
'prepublish'
Done in 0.09s.
```
and with `--prod` flag:
```
PS C:\git\junk> yarn --prod
yarn install v0.15.1
info No lockfile found.
$ echo 'preinstall'
'preinstall'
success Nothing to install.
$ echo 'install'
'install'
$ echo 'postinstall'
'postinstall'
Done in 0.08s.
```

I'm also working through how to add unit tests for this and can hold merge for that is desired.

### CODE REVIEW

**Comment by FLGMwt** [comment]
Also #721 which might be a dupe.

**Comment by Kovensky** [comment]
Note that npm means to deprecate how prepublish currently works in npm 4.0, to be released this month: https://github.com/npm/npm/issues/10074

**Comment by FLGMwt** [comment]
@Kovensky Nice catch!

After reviewing conversation there, it looks like it's still pretty up in the air what npm plans to do exactly to change the behavior. I'd be up for porting whatever they implement if that's desired, but these changes at least get us closer to npm compatibility (and resolves issues for a few people migrating).

That said, I'm happy to remove `prepublish` and just get the install hooks in. Looking for guidance : )

**Comment by jamesjnadeau** [comment]
@FLGMwt awesome work on this!

IMHO, not having these hooks is a show stopper to a lot of projects using yarn.

I would say feature parity with npm is what you should be shooting for, and having prepublish work the same way is probably best.

**Comment by ljharb** [comment]
Unless every single lifecycle script functions exactly the same as it does on npm, then yarn is not a drop-in replacement for npm - which I understand to be the goal. That includes prepublish's awful behavior.

**Comment by billxinli** [comment]
@kittens Curious on when this fix will get pushed to a release. This fix is going to fix a lot of issues with modules that depends on these hooks

**Comment by Kovensky** [comment]
Just a note: `npm@2` will run `preinstall` scripts before installing dependencies, but `npm@3` runs `preinstall` only after all dependencies are installed.

This patch runs `preinstall` before installing dependencies.

**Comment by dominictarr** [comment]
@ljharb A beer says that prepublish isn't that big a problem, and this is a good way to find out.

**Comment by ljharb** [comment]
@dominictarr if you're right, I will buy you a whole case. But if there are non-zero packages that depends on it, that would be enough for it to be a huge problem.

**Comment by dominictarr** [comment]
in the browser world, not everything is completely compatible, and, well, it's annoying some times, but we survive. I wasn't around at the time when javascript was brand new... but I'm gonna hazard to suggest that "mutating" a little bit, could actually make something _better_.

And in any case, there isn't a _spec_ for npm just an implementation, however if there are more than one implementation, maybe it's time to start thinking about a spec. (maybe wait another 15 minutes though)

**Comment by lipis** [comment]
@dominictarr on point.. since there are no specs let's rethink some of the procedures and not blindly copy stuff from npm.. just because.

**Comment by ljharb** [comment]
All the things browsers agree upon *are* the spec - that's true in the JS standard as well as in browser standards. Since `npm` has been the only implementation for this long, what it does *is* the spec. If yarn deviates, yarn will lose out.

**Comment by curtisblackwell** [comment]
Any idea when we can expect the next release so we can rely on this functionality?

**Comment by jordansexton** [comment]
Any update on the status of a release including this?

**Comment by janusch** [comment]
I am wondering if this also works for the 'yarn-offline-mirror' feature?
E.g. in node-sass the postinstall will download the correct binaries, are they added to the offline-mirror?

Some clarification would be very helpful to me!

**Comment by lordgreg** [comment]
Yarn doesn't install selenium webdriver when installing node module `protractor`. Using `npm install protractor` works as it should.

**Comment by ndbroadbent** [comment]
Hello, I am testing the `yarn` nightly build (v0.22.0-20170215.1538), and this doesn't seem to be working for me. Or maybe I just don't understand what it should be doing.

I have forked a package and am trying to install it from GitHub:

```
yarn add github:ndbroadbent/redux-persist-migrate
```

This `package.json` contains a prepublish line:

```
"prepublish": "npm run clean && npm run build"
```

This is not being run during the installation. I would expect this to be run, since GitHub is only for source code, and people don't usually check in the build artifacts.

I just read through [this issue on npm](https://github.com/npm/npm/issues/3055), and it looks like npm also doesn't run the `prepublish` script. I think `npm` should run this script, and I think `yarn` should, too.

Or should I just add this step as a `preinstall` hook on my own fork? Or just run the `preinstall` step myself and check in the built files?

**Comment by jamesjnadeau** [comment]
@ndbroadbent: is `preinstall` what you are looking for?

**Comment by ndbroadbent** [comment]
@jamesjnadeau I tried adding a `preinstall` hook, but that doesn't seem to work either. `yarn` is not even running the `prepublish` or `preinstall` hooks when installing from a local directory. When I run: `npm i ../redux-persist-migrate`, I see it runs the `prepublish` and `preinstall` hooks. 

`npm i ndbroadbent/redux-persist-migrate` doesn't run those hooks, and neither does `yarn add ndbroadbent/redux-persist-migrate`.

So I guess the only way is to push a new branch with the build artifacts checked in?

**Pull request merged**
