### PR TITLE
yarn search

### PR DESCRIPTION
**Pull request by maticzav**
## Yarn search (Emma)

- This PR implements live package search in Yarn CLI.

Check `emma-cli` for usage example (https://github.com/maticzav/emma-cli)

### TODO:
 - [x] Trigger package install in the end (`yarn add`).
 - [x] First line is repeated two times (not being removed).

screen shot 2018-03-10 at 19 19 52

### CODE REVIEW

**Comment by cpojer** [comment]
Thanks for adding this. It seems that it makes Yarn significantly larger – do you think there is any way we could align dependencies to reduce the size impact to something like 100k?

**Comment by BYK** [comment]
The main dependency here I think is `algoliasearch`. The full version of it seems to be around 190kb and the lite version is about 117kb: https://github.com/algolia/algoliasearch-client-javascript/blob/develop/dist/algoliasearchLite.js

If we can only use that, I think we can ship this pretty efficiently. What do you all think?

**Comment by BYK** [comment]
ping @maticzav

**Comment by BYK** [comment]
pingx2 @maticzav

**Comment by maticzav** [comment]
Hi 👋,
Sorry for the late reply. I've been extremely busy lately. I will check out the issue during the weekend and update the PR afterwards.

**Pull request closed without merging**
