### PR TITLE
check.js: Ignore dedup warnings for bundled dependencies

### LINKED ISSUE #3299: `yarn check` after clean `yarn install` reports errors
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running `yarn check` after a fresh `yarn install` (cleared cache, no `node_modules`, no lockfile present) reports an error.

**If the current behavior is a bug, please provide the steps to reproduce.**
package.json at https://github.com/jasonewang/yarn-check-test

Sample CLI output below
```
~/g/yarn-check-test ❯❯❯ rm -rf node_modules yarn.lock
~/g/yarn-check-test ❯❯❯ yarn cache clean
yarn cache v0.23.3
success Cleared cache.
✨  Done in 3.12s.
~/g/yarn-check-test ❯❯❯ yarn install
yarn install v0.23.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 91.82s.
~/g/yarn-check-test ❯❯❯ yarn check
yarn check v0.23.3
warning "nyc#archy@^1.0.0" could be deduped from "1.0.0" to "archy@1.0.0"
warning "nyc#arrify@^1.0.1" could be deduped from "1.0.1" to "arrify@1.0.1"
warning "nyc#caching-transform@^1.0.0" could be deduped from "1.0.1" to "caching-transform@1.0.1"
warning "nyc#convert-source-map@^1.3.0" could be deduped from "1.5.0" to "convert-source-map@1.5.0"
warning "nyc#debug-log@^1.0.1" could be deduped from "1.0.1" to "debug-log@1.0.1"
warning "nyc#default-require-extensions@^1.0.0" could be deduped from "1.0.0" to "default-require-extensions@1.0.0"
warning "nyc#find-cache-dir@^0.1.1" could be deduped from "0.1.1" to "find-cache-dir@0.1.1"
warning "nyc#find-up@^1.1.2" could be deduped from "1.1.2" to "find-up@1.1.2"
warning "nyc#foreground-child@^1.5.3" could be deduped from "1.5.6" to "foreground-child@1.5.6"
warning "nyc#glob@^7.0.6" could be deduped from "7.1.1" to "glob@7.1.1"
warning "nyc#istanbul-lib-coverage@^1.1.0" could be deduped from "1.1.0" to "istanbul-lib-coverage@1.1.0"
warning "nyc#istanbul-lib-hook@^1.0.6" could be deduped from "1.0.6" to "istanbul-lib-hook@1.0.6"
warning "nyc#istanbul-lib-instrument@^1.7.1" could be deduped from "1.7.1" to "istanbul-lib-instrument@1.7.1"
warning "nyc#istanbul-lib-report@^1.1.0" could be deduped from "1.1.0" to "istanbul-lib-report@1.1.0"
warning "nyc#istanbul-lib-source-maps@^1.2.0" could be deduped from "1.2.0" to "istanbul-lib-source-maps@1.2.0"
warning "nyc#istanbul-reports@^1.1.0" could be deduped from "1.1.0" to "istanbul-reports@1.1.0"
warning "nyc#md5-hex@^1.2.0" could be deduped from "1.3.0" to "md5-hex@1.3.0"
warning "nyc#merge-source-map@^1.0.2" could be deduped from "1.0.3" to "merge-source-map@1.0.3"
warning "nyc#micromatch@^2.3.11" could be deduped from "2.3.11" to "micromatch@2.3.11"
warning "nyc#mkdirp@^0.5.0" could be deduped from "0.5.1" to "mkdirp@0.5.1"
warning "nyc#resolve-from@^2.0.0" could be deduped from "2.0.0" to "resolve-from@2.0.0"
warning "nyc#rimraf@^2.5.4" could be deduped from "2.6.1" to "rimraf@2.6.1"
warning "nyc#signal-exit@^3.0.1" could be deduped from "3.0.2" to "signal-exit@3.0.2"
warning "nyc#spawn-wrap@1.2.4" could be deduped from "1.2.4" to "spawn-wrap@1.2.4"
warning "nyc#test-exclude@^4.1.0" could be deduped from "4.1.0" to "test-exclude@4.1.0"
warning "nyc#yargs-parser@^5.0.0" could be deduped from "5.0.0" to "yargs-parser@5.0.0"
warning "nyc#yargs#decamelize@^1.1.1" could be deduped from "1.2.0" to "decamelize@1.2.0"
warning "nyc#yargs#get-caller-file@^1.0.1" could be deduped from "1.0.2" to "get-caller-file@1.0.2"
warning "nyc#yargs#os-locale@^1.4.0" could be deduped from "1.4.0" to "os-locale@1.4.0"
warning "nyc#yargs#read-pkg-up@^1.0.1" could be deduped from "1.0.1" to "read-pkg-up@1.0.1"
warning "nyc#yargs#require-directory@^2.1.1" could be deduped from "2.1.1" to "require-directory@2.1.1"
warning "nyc#yargs#require-main-filename@^1.0.1" could be deduped from "1.0.1" to "require-main-filename@1.0.1"
warning "nyc#yargs#set-blocking@^2.0.0" could be deduped from "2.0.0" to "set-blocking@2.0.0"
warning "nyc#yargs#string-width@^1.0.2" could be deduped from "1.0.2" to "string-width@1.0.2"
warning "nyc#yargs#which-module@^1.0.0" could be deduped from "1.0.0" to "which-module@1.0.0"
warning "nyc#yargs#y18n@^3.2.1" could be deduped from "3.2.1" to "y18n@3.2.1"
warning "nyc#yargs#yargs-parser@^5.0.0" could be deduped from "5.0.0" to "yargs-parser@5.0.0"
error "nyc#yargs#cliui" is wrong version: expected "3.2.0", got "2.1.0"
warning "nyc#yargs#cliui#center-align@^0.1.1" could be deduped from "0.1.3" to "center-align@0.1.3"
warning "nyc#yargs#cliui#right-align@^0.1.1" could be deduped from "0.1.3" to "right-align@0.1.3"
warning "chokidar#fsevents#node-pre-gyp@^0.6.29" could be deduped from "0.6.34" to "node-pre-gyp@0.6.34"
info Found 40 warnings.
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```
The version of `cliui` installed at `node_modules/nyc/node_modules/yargs/node_modules/cliui` is version `3.2.0`, while the version installed at `node_modules/cliui` is `2.1.0`.

**What is the expected behavior?**
I'd expect `yarn check` to report no errors so `yarn check` can be used to verify that package.json and the lockfile are in sync.
**Please mention your node.js, yarn and operating system version.**
macOS 10.12.4
yarn v0.23.3
node v7.9.0

### PR DESCRIPTION
**Pull request by rufman**
Any package with bundledDependencies will be added to a hash of bundled
deps, which are used to check against when printing dedup warnings.
This is because bundled dependencies could result in duplications which
we would otherwise detect as false positives.

Fixes #3299

**Summary**
`yarn check` shouldn't return dedup warnings for any bundled dependencies, such as in the case of nyc.

**Test plan**
A simple `package.json` with just nyc, will return 41 warnings for packages present in nyc's `packageJson.bundledDependencies` when doing `yarn check` on the current master. When doing `yarn check` on this commit, no warnings are returned, since the dedup warnings resulting from nyc's bundled dependencies are ignored.

### CODE REVIEW

**Comment by rufman** [comment]
I seem to have issues with continuous integration timing out on different tasks on every rebuild attempt. Is there a way to get the build to pass?

**Comment by bestander** [comment]
@rufman, thanks for the fix, looks great.
But could you come up with a more focused test?
nic produces a 1000 lines lockfile, test fixtures like that slow down tests runtime and make CI less stable.

Also you need to actually add code to the https://github.com/yarnpkg/yarn/blob/master/__tests__/commands/check.js that would execute the fixture and verify that warning is not printed.

**Comment by rufman** [comment]
Ok, so I assume I would need to publish some test package that only has one dependency and one bundled dependency.

**Comment by bestander** [comment]
Probably no need to publish, you can commit a .tgz file in the test
fixtures

**Comment by rufman** [comment]
@bestander I've rebased and added a test. The fixture now only contains one bundled dependency, so it should be much lighter.

**Comment by bcoe** [comment]
@rufman awesome work, thanks 👍

**Pull request merged**
