### PR TITLE
add cache dir command to output path to cache directory

### PR DESCRIPTION
**Pull request by kittens**

### CODE REVIEW

**Comment by cpojer** [comment]
why is this `ls`? Is there something more appropriate? Also, if you add features, please create an issue about it on the website repo too so somebody can take care of it and we don't end up with undocumented cli features: https://github.com/yarnpkg/website/issues

**Comment by cpojer** [comment]
(Approved because I trust you to find the best name).

**Comment by kittens** [comment]
Oops, was meant to be `dir`.

**Comment by chicoxyzzy** [comment]
this causes flow erros
```
src/cli/commands/cache.js:35
 35:     console.log(config.packagesRoot);
                            ^^^^^^^^^^^^ property `packagesRoot`. Property not found in
 35:     console.log(config.packagesRoot);
                     ^^^^^^ Config


Found 1 error
```

**Pull request merged**
