### PR TITLE
CONTRIBUTING: add setup instructions [skip ci]

### PR DESCRIPTION
**Pull request by hzoo**
Adding setup instructions similar to what we have in babel https://github.com/babel/babel/blob/master/CONTRIBUTING.md#setup

### CODE REVIEW

**Comment by Daniel15** [comment]
> First check that `yarn` is installed globally with `npm install yarn --global`

It seems pretty confusing to have Yarn installed globally when working on Yarn itself :)

Additionally the npm module is just supposed to be a fallback - Ideally people should be using the Windows installer or Linux packages (or Homebrew once we have that) to install a release build of Yarn

**Comment by hzoo** [comment]
Ah ok wasn't sure

**Comment by hzoo** [comment]
Ok I'l just link to the install docs?

**Comment by zetoke** [comment]
>`npm install yarn --global`

yarnpkg, not yarn

**Comment by hzoo** [comment]
it's actually `yarn` now (either way I removed that and used the link instead)

**Comment by zetoke** [comment]
@hzoo Oh, I see. Thanks for information!

**Pull request merged**
