### PR TITLE
feat: allows yarn config set to override package.json config keys

### PR DESCRIPTION
**Pull request by cwmoo740**
feature in npm: https://docs.npmjs.com/files/package.json#config

issue: https://github.com/yarnpkg/yarn/issues/2989

**Summary**

The goal of this PR is to allow the same feature as found in npm:

package.json

```json
"name": "yarn",
"config": {
    "whatever": "test"
}
```

`yarn config set yarn:whatever production`

should make the environment variable

`npm_package_config_whatever === 'production'`

**Test plan**

Automated tests are incoming. Tested manually with `yarn env`.

Are these changes too much or is there a better way of accomplishing this?

### CODE REVIEW

**Comment by arcanis** [comment]
Looks good to me. Can you make sure the tests pass and add a new one?

**Comment by cwmoo740** [comment]
will do! thanks.

**Comment by cwmoo740** [comment]
I see that node4 is failing but I can't get a single test to run locally with node4 on upstream master anyway. Is that still supported?

**Comment by arcanis** [comment]
Yep, node 4 is still supported (cf CircleCI results for master - they're green bar a few timeouts here and there when we try to access the network). I think the error you've had might be transient (not enough memory to do a read? weird ...), so I'll restart your tests just in case.

**Comment by arcanis** [comment]
I'm not sure what exactly, but there's definitely something wrong in this PR ... maybe a memory leak somewhere? 😐

**Comment by cwmoo740** [comment]
I'll try to get these running locally again on node 4 again.

**Comment by cwmoo740** [comment]
The test setup I used is also here:

https://github.com/yarnpkg/yarn/blob/615ee94b0d88dfbd728d03114aa031cd11e838e1/__tests__/config.js#L9

If I'm not mistaken, calling `new ConsoleReporter` for every test was causing a memory leak when I copied that configuration.

**Comment by cwmoo740** [comment]
So here's something fun - I reverted back to the older version of the test and it's passing now. What do we do?

**Comment by cwmoo740** [comment]
@arcanis the issues with he test suite seem to be resolved - can this be reviewed again?

**Comment by cwmoo740** [comment]
@arcanis are there any additional reviewers that could look at this?

**Comment by arcanis** [comment]
Must have been a transient issue then, but it certainly looked weird. Have pushed a commit on your branch, I'll see how it goes and merge your PR.

**Comment by arcanis** [comment]
Ok, I fucked up by trying to run prettier and now I don't have the perms anymore to push on the master branch of your PR (because I pushed the real master there, so there isn't any change anymore, so Github lost track of the PR...). I opened #5518 that contains your commit plus mine. Let me know if I can merge it or if you prefer to open a new PR to get the contributor badge.

Sorry about this 😞

**Comment by cwmoo740** [comment]
No problem. That pr looks good. Thanks for helping me get it merged.

**Comment by arcanis** [comment]
Merged! Thanks again! 😃

**Pull request closed without merging**
