### PR TITLE
Backport to 0.18: Fix scoped bin paths (#2163)

### PR DESCRIPTION
**Pull request by LinusU**
* Add failing tests for bin path normalisation from scoped package name
* Add fix for bin normalisation for scoped packages

**Summary**

Backport "Fix scoped bin paths" (#2163) to the 0.18 release branch

### CODE REVIEW

**Comment by bestander** [comment]
Oh snap, this uses a newer version of some dependency then committed to cache.
2 ways I see here: refresh the network cache (`rm -rf __tests__/fixtures/request-cache/` and run tests locally and then commit the new files) or disable the new tests.
Both ways work for me in this case.

**Comment by LinusU** [comment]
On it 👌

**Comment by LinusU** [comment]
Looks like something timed out on circleci 😕 maybe restarting the build will take care of it?

screen shot 2016-12-21 at 1 52 21 pm

**Comment by bestander** [comment]
Happens, restarted

**Comment by LinusU** [comment]
Thank you!

**Pull request merged**
