### PR TITLE
fix: Use cmdshim instead of symlink on win32 in base-fetcher

### LINKED ISSUE #6604: Yarn install error on Azure App Service
Using yarn version 1.12.1 on Azure App Service errors during installation.

**What is the current behavior?**
Error during installation of dependencies
```
00:06:35.319 remote: Selected node.js version 8.11.1. Use package.json file to choose a different version.
00:06:35.319 remote: Selected npm version 5.6.0
00:06:35.320 remote: Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
00:06:35.320 remote: Verifying Yarn Install.
00:06:37.221 remote: D:\local\AppData\npm\yarnpkg -> D:\local\AppData\npm\node_modules\yarn\bin\yarn.js
00:06:37.221 remote: D:\local\AppData\npm\yarn -> D:\local\AppData\npm\node_modules\yarn\bin\yarn.js
00:06:37.221 remote: + yarn@1.12.1
00:06:37.221 remote: added 1 package in 0.89s
00:06:37.221 remote: Installing Yarn Packages.
00:06:37.786 remote: yarn install v1.12.1
00:06:38.722 remote: [1/5] Validating package.json...
00:06:38.722 remote: [2/5] Resolving packages...
00:06:39.289 remote: [3/5] Fetching packages...
00:06:39.856 remote: info If you think this is a bug, please open a bug report with the information provided in "D:\\home\\site\\wwwroot\\yarn-error.log".
00:06:39.857 remote: error An unexpected error occurred: "EPERM: operation not permitted, symlink 'D:\\local\\LocalAppData\\Yarn\\Cache\\v3\\npm-esprima-4.0.0-4499eddcd1110e0b218bacf2fa7f7f59f55ca804\\node_modules\\esprima\\bin\\esparse.js' -> 'D:\\local\\LocalAppData\\Yarn\\Cache\\v3\\npm-esprima-4.0.0-4499eddcd1110e0b218bacf2fa7f7f59f55ca804\\node_modules\\esprima\\.bin\\esparse'".
```
Yarn error log attached for more info.
[yarn-error.log](https://github.com/yarnpkg/yarn/files/2534053/yarn-error.log)

**What is the expected behavior?**
Correct installation

**Please mention your node.js, yarn and operating system version.**
Node: 8.11.1
Yarn: 1.12.1
OS: Windows

### PR DESCRIPTION
**Pull request by yoadsn**
**Summary**
This is an implementation of the suggestion by @arcanis to fix #6604. In short, on win32 platforms, the symlink requires elevated privileges. This fix would use the cmdshim to work around the need for the symlink specifically on the `base-fetcher` module.

**Test plan**
Same test suit was used since platform emulation is not included today.

### CODE REVIEW

**Comment by arcanis** [comment]
Perfect, thanks!

**Comment by arcanis** [comment]
I fixed the cache versioning, but it seems there are issues with two tests on Windows:

```
Summary of all failing tests
FAIL __tests__\commands\check.js
  ● --integrity should ignore comments and whitespaces in yarn.lock
    Error: ENOENT: no such file or directory, stat 'C:\Users\appveyor\AppData\Local\Temp\1\yarn-bundled-dep-check-1541114868149-0.6443591651832778\.yarn-cache\v4\npm-nyc-10.3.2-35563cb271637e2dc922a1145d8981e948a9f5c3\node_modules\nyc\bin\nyc.js' 
    Console output:
     [1/4] Resolving packages...
    [2/4] Fetching packages...
      185 |     }
      186 |   } catch (err) {
    > 187 |     throw new Error(`${err && err.stack} \nConsole output:\n ${out}`);
      188 |   } finally {
      189 |     reporter.close();
      190 |     await fs.unlink(cwd);
      
      
      at __tests__/commands/_helpers.js:187:11
          at Generator.throw (<anonymous>)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
  ● should ignore bundled dependencies
    Error: ENOENT: no such file or directory, stat 'C:\Users\appveyor\AppData\Local\Temp\1\yarn-bundled-dep-check-1541114868149-0.6443591651832778\.yarn-cache\v4\npm-nyc-10.3.2-35563cb271637e2dc922a1145d8981e948a9f5c3\node_modules\nyc\bin\nyc.js' 
    Console output:
     [1/4] Resolving packages...
    [2/4] Fetching packages...
      185 |     }
      186 |   } catch (err) {
    > 187 |     throw new Error(`${err && err.stack} \nConsole output:\n ${out}`);
      188 |   } finally {
      189 |     reporter.close();
      190 |     await fs.unlink(cwd);
      
      
      at __tests__/commands/_helpers.js:187:11
          at Generator.throw (<anonymous>)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
Test Suites: 1 failed, 87 passed, 88 total
Tests:       2 failed, 3 skipped, 1195 passed, 1200 total
```

**Comment by yoadsn** [comment]
Able to repro on a windows machine.
@arcanis Obviously, the `check` command is not happy about the shim usage. I'm not proficient enough 
with the code and the check logic to determine if it's the way check is implemented or the checks should be different on win32. Maybe its the test suit itself who should have different expectations on win32.
Regardless, since the shim does not do what a symlink does - there might be other places where the tests do not cover well and yarn would still fail due to the missing real symlinks.
What would you suggest? Any other approach or should we keep going this path? Getting elevated privileges on Azure sandbox seems out of the question.

**Comment by arcanis** [comment]
Ok, I think I've found the problem. It's just that the test fixture in those tests is only partial, meaning that the destination of the binary link doesn't actually exist. The new code that creates it expects it to do (probably because of `lockMutex`, I'd say), and thus crashes. I'm not sure why it crashes during the fetch step (I'd have expected it to happen during the linking), though.

Will fix that next week.

**Comment by yoadsn** [comment]
So again, since I read this code-base for the first time - In the failing fixture's `runInstall`, which creates an `Install` and calls `init()` on it would cause a bunch of steps to be queued and executed. The first queued step is the resolve, the second queued step would be a `fetch` which would in turn call the `fetch()` on the fetcher. This `package-fetcher` would use the patched code in `base-fetcher` which expects the target bin file to exist but is not since the fixture does not run something which usually would have been.
The linker should be the one calling `linkBin` which would place the file where it should be. Since fetch runs before that (on this fixture at least) - this causes the missing file failure.
Did I understand correctly?
Anyway I can help further this?

**Pull request merged**
