### PR TITLE
Fix issue #573 - private git ssh urls

### PR DESCRIPTION
**Pull request by f-sign**
**Summary**

Yarn didn't support certain formats of git urls, especially the ones with colon on it.

**Test plan**

Added tests to reproduce the problem and these tests all pass.

### CODE REVIEW

**Comment by BryanCrotaz** [comment]
@wyze the CI seems to have failed due to missing public keys - can you re-run?

**Comment by wyze** [comment]
@BryanCrotaz, they are rerunning now.

**Comment by toefraz** [comment]
@wyze it seems like CI failed again due to key errors installing from GitHub

**Comment by chrisirhc** [comment]
Any chance someone with the permissions can re-run the tests?

**Comment by wyze** [comment]
Kicked off a rebuild on Travis.

**Comment by BryanCrotaz** [comment]
@wyze Failed again with `Permission denied (publickey)`

**Comment by wyze** [comment]
Other builds are passing. This PR touches the `hosted-git-resolver` which could cause this test to fail. @f-sign, could you please check into the test failure?

**Comment by BryanCrotaz** [comment]
@wyze it's not getting as far as running the tests:
```
(node:8486) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error: Command failed.
Exit code: 128
Command: git
Arguments: clone ssh://git@github.com/substack/node-mkdirp.git /tmp/yarn-install-github-0.3094830624742697/.yarn-cache/.tmp/f87fb05e5feff74616d48fa358e1d0ce
Directory: /home/travis/build/yarnpkg/yarn
Output:
Cloning into '/tmp/yarn-install-github-0.3094830624742697/.yarn-cache/.tmp/f87fb05e5feff74616d48fa358e1d0ce'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
    at MessageError (/home/travis/build/yarnpkg/yarn/src/errors.js:5:5)
    at SpawnError (/home/travis/build/yarnpkg/yarn/src/errors.js:14:1)
    at ChildProcess.proc.on.code (/home/travis/build/yarnpkg/yarn/src/util/child.js:86:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12) 
```
The PR doesn't touch the package.json so I can't see how this PR would break it

**Comment by BryanCrotaz** [comment]
@wyze DOH!!!! I'm an idiot. Ignore that last message. I'll ask Flavio to take another look.

**Comment by toefraz** [comment]
Any updates on why the CI tests are failing?

**Comment by wyze** [comment]
@toefraz, waiting to hear back from @f-sign to take a look. Will also need a rebase.

**Comment by BryanCrotaz** [comment]
@f-sign and I have been looking at it - can't work out how taking some comments out has caused the build to fail

**Comment by cascornelissen** [comment]
@BryanCrotaz, any updates on this? What's the plan?

**Comment by f-sign** [comment]
Sorry for the delay... Some deadlines here.

We've run the tests locally against latest master and our PR branch. We get the same 3 failures on both:

MASTER eb66b9c3dfe3e32a95f51c81f483d00c4beb8ad7 
```
Summary of all failing tests
 FAIL  __tests__\commands\cache.js (120.793s)
  ● write cache-folder config into .yarnrc file

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at Timeout._onTimeout (node_modules\jest-jasmine2\vendor\jasmine-2.4.1.js:1912:23)
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)

  ● cache-folder flag has higher priorities than .yarnrc file

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at Timeout._onTimeout (node_modules\jest-jasmine2\vendor\jasmine-2.4.1.js:1912:23)
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)

 FAIL  __tests__\commands\add.js (154.473s)
  ● add with new dependency should be deterministic 3

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at Timeout._onTimeout (node_modules\jest-jasmine2\vendor\jasmine-2.4.1.js:1912:23)
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)


Test Suites: 2 failed, 1 skipped, 38 passed, 40 of 41 total
Tests:       3 failed, 19 skipped, 292 passed, 314 total
Snapshots:   50 passed, 50 total
Time:        177.557s
Ran all test suites.
```

Mine 97800171199aea1b99f2d5df819923544999afd7
```
Summary of all failing tests
 FAIL  __tests__\commands\cache.js (120.795s)
  ● write cache-folder config into .yarnrc file

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at Timeout._onTimeout (node_modules\jest-jasmine2\vendor\jasmine-2.4.1.js:1912:23)
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)

  ● cache-folder flag has higher priorities than .yarnrc file

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at Timeout._onTimeout (node_modules\jest-jasmine2\vendor\jasmine-2.4.1.js:1912:23)
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)

 FAIL  __tests__\commands\add.js (152.401s)
  ● add with new dependency should be deterministic 3

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at Timeout._onTimeout (node_modules\jest-jasmine2\vendor\jasmine-2.4.1.js:1912:23)
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)


Test Suites: 2 failed, 1 skipped, 38 passed, 40 of 41 total
Tests:       3 failed, 19 skipped, 296 passed, 318 total
Snapshots:   50 passed, 50 total
Time:        175.15s
Ran all test suites.
```

The first time I submitted the pull request it passed all tests and I was asked to remove some commented out console.log(). After removing then, it is not passing one of the tests. I am running the tests on Windows.
Any advice?

**Comment by BryanCrotaz** [comment]
@wyze any thoughts on @f-sign's test results? Basically getting same failures on master as on our PR branch, and different failures to those on Travis.

**Comment by bestander** [comment]
@f-sign could this be network related?
I test on my mac locally:
```
$ yarn test-ci
Test Suites: 1 skipped, 42 passed, 42 of 43 total
Tests:       19 skipped, 317 passed, 336 total
Snapshots:   50 passed, 50 total
Time:        164.015s
```

What node version do you use?

**Comment by f-sign** [comment]
@bestander I'm using Node v6.9.1 on Windows.
Did you run the tests on my commit or on master? On my first submission, all tests passed (including travis-ci). Then, upon removing some commented out console.log() calls, it's failing on travis-ci.
If you haven't, could you please test my commit on your machine?

**Comment by bestander** [comment]
@f-sign, I noticed that on Windows I have a few tests timing out, too.
But I did not have time to investigate why, especially that appveyor CI (windows) is running fine on your branch.

Just ran tests locally for your branch
```
Test Suites: 2 skipped, 34 passed, 34 of 36 total
Tests:       19 skipped, 269 passed, 288 total
Snapshots:   50 passed, 50 total
Time:        93.155s, estimated 102s
Ran all test suites.
✨  Done in 107.28s.
```

**Comment by bestander** [comment]
I think your test failed on Travis for some random reasons.
Github may throttle anonymous requests at peak times.

**Comment by bestander** [comment]
Maybe the new tests have a high chance of modifying some git global settings concurrently?

**Comment by epmatsw** [comment]
On macOS 10.12.2, node 7.2.0, and npm 3.10.9, I had one run that had a single failure (something about `Cannot find module '../lib-legacy/constants'`). After removing node_modules and re-running yarn, I ran the tests again and got that failure plus the async failures mentioned above for `install with arg that has install scripts` and `install should hoist nested bin scripts`.

**Comment by BryanCrotaz** [comment]
@wyze any idea why we're all getting different sets of test failures with the same source?

**Comment by gaving** [comment]
I'm desperate for this functionality so tried installing this pull with:-

`npm install https://github.com/yarnpkg/yarn#pull/1816/head`

But just ended up with the same error @epmatsw has posted:-

    Step 15 : RUN yarn add git+ssh://git@git.local:test/client-node.git
     ---> Running in 9551d6b4c139
    module.js:471
        throw err;
        ^

    Error: Cannot find module '../lib-legacy/constants'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/yarn/bin/yarn.js:9:17)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
    The command '/bin/sh -c yarn add git+ssh://git@git.local:test/client-node.git' returned a non-zero code: 1
    ERROR: Build failed: exit code 1

**Comment by gurpreetatwal** [comment]
@gaving I also tried pulling as well and got that error at first, but if you manually run `npm run build` prior to running `npm test` that error disappears

**Comment by BryanCrotaz** [comment]
@wyze any clues as to what we can fix to get this merged?

**Comment by bestander** [comment]
@f-sign, quite a few tests instability issues were fixed recently, could you rebase?
Ideally after https://github.com/yarnpkg/yarn/pull/2370 is merged.

**Comment by chrisirhc** [comment]
Looks like the error is centered around:
```
 Error
      Error: Error: Command failed.
      Exit code: 128
      Command: git
      Arguments: clone ssh://git@github.com/substack/node-mkdirp.git /tmp/yarn-install-github-1483469740695-0.6846000772434384/.yarn-cache/.tmp/f87fb05e5feff74616d48fa358e1d0ce
      Directory: /home/travis/build/yarnpkg/yarn
      Output:
      Cloning into '/tmp/yarn-install-github-1483469740695-0.6846000772434384/.yarn-cache/.tmp/f87fb05e5feff74616d48fa358e1d0ce'...
      Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
      Permission denied (publickey).
      fatal: Could not read from remote repository.
      
      Please make sure you have the correct access rights
      and the repository exists.
```

Does this change make it so that previous behavior that did: `git clone https://github.com/substack/node-mkdirp.git` now does `git clone ssh://git@github.com/substack/node-mkdirp.git` instead? And it's failing due to SSH credentials that accepted by github.com ?

**Comment by bestander** [comment]
This one got a bad rebase, merged via #2384.
Closing this one

**Comment by Gudahtt** [comment]
Does this solve #513 ? I noticed that #513 is locked and still links here.

**Pull request closed without merging**
