### PR TITLE
Replace `.includes` with `.indexOf` for older Node 4 versions

### PR DESCRIPTION
**Pull request by wyze**
**Summary**

It was reported in https://github.com/yarnpkg/yarn/pull/1792#issuecomment-260364519 that this code did not work on Node v4.

**Test plan**

All tests still pass. Confirmed working on Node v4 here: https://github.com/yarnpkg/yarn/pull/1792#issuecomment-260369372

### CODE REVIEW

**Comment by wyze** [comment]
Failure on CircleCI is not related. Was a timeout with `normalize-manifest` test.

**Comment by develar** [comment]
Maybe it is better to use [babel-plugin-array-includes](https://www.npmjs.com/package/babel-plugin-array-includes) to avoid such code?

**Comment by ljharb** [comment]
Or https://npm us.com/array-includes :-p then you're version-independent.

**Comment by develar** [comment]
@ljharb `array-includes` it is runtime dependency, babel solution has zero-overhead ;)

**Pull request merged**
