### PR TITLE
hide verbose error message when no manifest found

### LINKED ISSUE #824: Typing only 'yarn'
**Do you want to request a *feature* or report a *bug*?**
Feature, well it is an enhancement. 
**What is the current behavior?**
When i type yarn for first time on console, the output of typing just yarn on a new directory is too scary.
screen shot 2016-10-12 at 4 27 58 pm

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Well decrease in verbosity and also automatically output ```yarn --help``` commands

### PR DESCRIPTION
**Pull request by mikaoelitiana**
yarn command will not show verbose message when no package.json or
bower is found

fixes #824

### CODE REVIEW

**Comment by kittens** [comment]
We use this in a bunch of places and this validation is really important. I think it'd be best if we suppressed this error when we look for the root manifest in `cli/commands/install.js`.

**Comment by mikaoelitiana** [comment]
I see the problem is at the end when executing `await executeLifecycleScript(config, 'prepublish');`. Should we check the existence of root manifest before executing this then?

**Comment by kittens** [comment]
Can you please rebase

**Comment by mikaoelitiana** [comment]
This seems to be fixed in 0.16.1

**Pull request closed without merging**
