### PR TITLE
Translate README into Chinese

### PR DESCRIPTION
**Pull request by ChuanfengZhang**
Translate README.md into Chinese for Chinese native : )

### CODE REVIEW

**Comment by kittens** [comment]
I'm not sure how we want to handle i18n. cc @thejameskyle

**Comment by Daniel15** [comment]
I like this idea. We could have links to other languages at the top of the README.

**Comment by thejameskyle** [comment]
Committing translations directly never works out well. I'd rather link off to the translated versions of the website which contain the same content about what the project is and how to contribute.

**Comment by bestander** [comment]
As @thejameskyle said we'll store language specific docs in the website repo.
Feel free to discuss this here.

**Pull request closed without merging**
