### PR TITLE
moved ghr out of project

### LINKED ISSUE #1203: [infra] install bundle is too large
.tar.gz contains `ghr` from CircleCI.
We need to download it in parent folder to omit it from build

### PR DESCRIPTION
**Pull request by bestander**
fixes #1203.
ghr should be downloaded outside of the project source

### CODE REVIEW

**Comment by bestander** [comment]
Let me try but I am not sure I have access to /usr/local/bin, and

**Comment by bestander** [comment]
@Daniel15, looks like not allowed to because of Circle setup https://circleci.com/gh/yarnpkg/yarn/1561?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Daniel15** [comment]
We have permission to use apt-get which installs executables in /usr/bin,
so /usr/local/bin should be fine as long as you use sudo

**Comment by bestander** [comment]
@Daniel15 that worked :)

**Comment by Daniel15** [comment]
This looks good! Thank you 😄

**Comment by kittens** [comment]
There's a lot of complexity here, why can't we just add `ghr` and `ghr.zip` to `.npmignore`?

**Comment by Daniel15** [comment]
Ha, I think that'd work too. The advantage in this diff is that ghr is cached so it won't be downloaded again every time.

**Comment by bestander** [comment]
Yeah, adding ghr.zip and ghr to gitignore or npmignore would be easier but I didn't want to leak this specific tool we install only on Circle to leak into the repo in some way.
Also as Daniel noted, ghr is cached now and should not be downloaded on every build

**Pull request merged**
