### PR TITLE
Fail if has integrityError with --frozen-lockfile

### PR DESCRIPTION
**Pull request by NameFILIP**
**Summary**
Fixes the https://github.com/yarnpkg/yarn/issues/4440

**Test plan**

At the same commit as in the issue, but with the expected behavior:
```
➜  my-repo git:(dfc927c58) git status
HEAD detached at dfc927c58
nothing to commit, working tree clean

➜  my-repo git:(dfc927c58) yarn install
yarn install v1.0.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 16.34s.

➜  my-repo git:(dfc927c58) git status
HEAD detached at dfc927c58
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   yarn.lock

no changes added to commit (use "git add" and/or "git commit -a")

➜  my-repo git:(dfc927c58) ✗ git checkout yarn.lock
➜  my-repo git:(dfc927c58) git status
HEAD detached at dfc927c58
nothing to commit, working tree clean

➜  my-repo git:(dfc927c58) yarn install --frozen-lockfile
yarn install v1.0.2
[1/4] 🔍  Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### CODE REVIEW

**Comment by BYK** [comment]
Looks good. Can you also add a test for this?

**Comment by BYK** [comment]
@NameFILIP - do you need any help with tests?

**Comment by NameFILIP** [comment]
@BYK mainly, I need time, but if you can point me to the key files, that'd help

**Comment by BYK** [comment]
@NameFILIP I'd just extend or copy this: https://github.com/yarnpkg/yarn/blob/master/__tests__/commands/install/lockfiles.js#L57-L70

**Comment by BYK** [comment]
@NameFILIP need any help?

**Comment by BYK** [comment]
@kaylieEB do you think you can take this PR over?

**Comment by kaylieEB** [comment]
@BYK sure, I'll have it by this weekend!

**Comment by kaylieEB** [comment]
left a comment on original issue, https://github.com/yarnpkg/yarn/issues/4440

**Pull request closed without merging**
