### PR TITLE
Add aliases tests

### LINKED ISSUE #1257: Add shorthand aliases to yarn add
**Do you want to request a _feature_ or report a _bug_?**

_feature_

**What is the expected behavior?**
Add shorthand for `--save --save-exact` and `--save-dev --save-exact` like `-SE` and `-DE`

**Please mention your node.js, yarn and operating system version.**

Yarn Version: `0.16.0`
OS: `Elementary OS`
Node Version: `v6.2.2`

### PR DESCRIPTION
**Pull request by olingern**
~**Summary**~
~Per a feature request in #1257, short hand aliases have been added to the yarn cli.~

~**Motivation**~
~Improve the ease of use of the yarn cli.~

Amended for addition of tests only.

### CODE REVIEW

**Comment by samccone** [comment]
@kittens this one is up to you :)

**Comment by bestander** [comment]
I am not sure if `a` is a good improvement over `add`.
@kittens, your call about a/add.

@olingern, can you rebase please?
I think tests are still good to add to guard against API breakages in the future.

**Comment by olingern** [comment]
@bestander I scrapped all of the alias for add and rebased.

**Comment by olingern** [comment]
Also, [this line](https://github.com/yarnpkg/yarn/pull/1420/files#diff-867becf4a9c2c6c6d4e7c1278750724eR29) is kind of unfortunate. Flow doesn't know about the parent conditional, and since the aliases object [is defined to accept null types](https://github.com/yarnpkg/yarn/blob/master/src/cli/aliases.js#L34), removing the conditional throws a linting / flow error. 

screen shot 2016-11-15 at 10 06 36 am

**Comment by olingern** [comment]
Hey, @bestander are you still interested in merging these tests or should I close this PR?

**Comment by bestander** [comment]
@olingern, I'd close it for now, sorry that you've spent time on it.
After thinking about this, I think we should not calcify API with tests yet, that would slow down changes later on.

**Comment by olingern** [comment]
@bestander Not problem. I'll keep the branch on my fork and can open another PR should the API be stable / unchanging enough to add tests around it.

**Pull request closed without merging**
