### PR TITLE
fix(linker): use lockfileFolder when creating bin links

### LINKED ISSUE #4359: Yarn Workspaces - binaries are linked incorrectly
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**

When using Yarn Workspaces, binaries are linked incorrectly when running `yarn install` in a specific package.

Setup:
1. package-a depends on webpack@3
2. package-b depends on webpack@1
3. package-c depends on webpack@1
4. Yarn Workspaces enabled

Steps:
run `yarn install` inside package-b

A repo demonstrating the issue is here: https://github.com/ohana54/yarn-bug

Result:
`package-b/node_modules/.bin/webpack` is linked to `package-a/node_modules/webpack/bin/webpack.js`

**What is the expected behavior?**
`package-b/node_modules/.bin/webpack` is linked to `[root-folder]/node_modules/webpack/bin/webpack.js`

**Please mention your node.js, yarn and operating system version.**
node v.6.11.0, yarn v1.0.1, Mac OSX 10.11.4

**Note:** this can also happen when the current state is correct, and then running `yarn add some-package` inside package-b.

EDIT: simpler steps to reproduce
EDIT 2: copied the steps from the repo, added another way to reproduce

### LINKED ISSUE #4513: `yarn add` with workspaces doesn't install to workspace root
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Running `yarn add foo` inside a workspace directory does two unexpected things;
1. it installs the newly added dependency in `/my-workspace/node_modules/foo`, whereas I would expect it to install it to the workspace root, e.g.: `/node_modules/foo`
2. it installs *all* other dependencies of `my-workspace` to `/my-workspace/node_modules`

**If the current behavior is a bug, please provide the steps to reproduce.**
See also: https://github.com/edorivai/workspace-test

1. Create an empty directory(`workspace-1`), and add a minimal `package.json` file.
2. In root `package.json`, set `"workspaces": [ "./*" ]`
3. Run:
```
cd workspace-1
yarn add lodash.assign
```
4. By now, I'd have (also see [screenshot](https://github.com/edorivai/workspace-test/blob/master/directory-structure.png))
```
/workspace-1
  /node_modules
    /lodash.assign
```

**What is the expected behavior?**
I would have expected

```
/node_modules
  /lodash.assign
/workspace-1
```
With node modules being installed at the root level.

**Please mention your node.js, yarn and operating system version.**
```
$ uname -srvo
Linux 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 GNU/Linux

$ lsb_release -rcd
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

$ node --version
v8.5.0

$ npm --version
5.3.0

$ yarn --version
1.0.2-20170921.1145
```

### LINKED ISSUE #4706: Root binaries get removed after installing a Workspace dependency
Reproducing on Yarn **1.20** and **1.21.**

**Minimal reproducible demo at [skidding/yarn-bin-missing](https://github.com/skidding/yarn-bin-missing)**

Steps to reproduce:

Step 1: Jest is installed in workspace root and binary is present after running `yarn`

```
> yarn
> ls node_modules/.bin/jest
# node_modules/.bin/jest
```

Step 2: Go to `foo` workspace and install Lodash

```
> cd cd packages/foo
> yarn add lodash
```

Step 3: Go to back to root and 💨 `node_modules/.bin` is gone.

```
> cd -
> ls node_modules/.bin/jest
ls: node_modules/.bin/jest: No such file or directory
```

### PR DESCRIPTION
**Pull request by jgoz**
**Summary**

Fixes #4706, fixes #4359, refs #4513. `this.config.cwd` was being used as the root for bin link paths, rather than `this.config.lockfileFolder`.

**Test plan**

- Added tests for `add` and `remove` commands (#4706)
- Added test for `install` command (#4359)

### CODE REVIEW

**Comment by edorivai** [comment]
@jgoz, I just checked #4513, and according to my test, the issue still exists.

**Comment by jgoz** [comment]
@edorivai OK, thanks for checking. I think that issue is probably related and will have a similar solution.

**Comment by edorivai** [comment]
@jgoz :+1: looking forward. With the exception of some minor issues, workspaces are very awesome until now!

**Comment by edmorley** [comment]
> Maybe fixes #4359 (I didn't test against the repro - @ohana54, could you test this branch?)

I can confirm that using the STR in https://github.com/yarnpkg/yarn/issues/4359#issuecomment-337906700 this no longer reproduces for me using a build from this PR branch, when it did before under yarn 1.2.1 🎉

**Comment by jgoz** [comment]
@edmorley Great! Thanks for testing that. I added a unit test covering #4359 to this branch.

**Comment by BYK** [comment]
Wow, this is great thank you! I'll also check #4289 with this patch.

**Pull request merged**
