### PR TITLE
Initialize package.json with default values if parameter is set

### LINKED ISSUE #637: yarn init -y
I use this option a lot to quickly start a new project.
I can open a PR to add it :)

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`yarn init -y` does not exist and returns:
```
👉  yarn init -y
yarn init v0.15.1
error This command doesn't require any arguments.
info Visit http://yarnpkg.com/en/docs/cli/init for documentation about this command.
```

**What is the expected behavior?**
`yarn init -y` should be possible to guarantee full compatibility with NPM https://docs.npmjs.com/cli/init

**Please mention your node.js, yarn and operating system version.**
Node v5.3.0
yarn 0.15.1
macOS Sierra

### PR DESCRIPTION
**Pull request by koddsson**
Add a `--yes|-y` flag to the `init` command to automatically create a `package.json` with the default values.

It makes initializing a new project faster! 😎 

Fixes #637

### CODE REVIEW

**Comment by koddsson** [comment]
This test failure seems to be happening on `master` as well.

**Comment by cpojer** [comment]
This is great, thank you! Please take a look at the install command and how the flags are used there: https://github.com/cpojer/yarn/blob/master/src/cli/commands/install.js

You can use `commander.option` to specify available flags for the command and then `flags.yes` (or similar) should work without custom detection of command line arguments.

Would you mind sending a PR to the website to document this feature as well?

**Comment by kittens** [comment]
Thank you so much for the PR @koddsson. Didn't see this PR before I merged #873 😞

**Comment by koddsson** [comment]
No worries @kittens 😊

**Pull request closed without merging**
