### PR TITLE
install package with file: protocol as default if it exists in the filesystem

### PR DESCRIPTION
**Pull request by voxsim**
This pull request should resolve https://github.com/yarnpkg/yarn/issues/605.

Some info:
- I added existsSync function to not spread async annotation everywhere
- I created an instance method normalize that 'do the stuff', in detail: 
  everytime we normalizePattern in package-request and it is a request we also normalize the range  (if it is a file it will preprend file: and do other stuff, read the comment on the method).
- normalizePattern is a static function and it is used in other classes, I prefered to do not touch this method

Let me know if you like it!
cheers,
Simon

### CODE REVIEW

**Comment by bestander** [comment]
The tests will pass when you rebase

**Comment by voxsim** [comment]
@bestander I will try to do the same with async in another pull request and after that we will decide which is the best :)

**Comment by bestander** [comment]
👍

**Comment by voxsim** [comment]
@bestander I rebased with master and I opened another pull request https://github.com/yarnpkg/yarn/pull/2723 ;)

**Comment by bestander** [comment]
#2723 is better :)

**Pull request closed without merging**
