### PR TITLE
`yarn outdated`: Use correct version key when looking up package type

### PR DESCRIPTION
**Pull request by evocateur**
**Summary**

``` sh
$ yarn init -y
$ yarn add @financial-times/n-bottle@1.0.0
$ yarn outdated
yarn outdated v0.16.1
error An unexpected error occured, please open a bug report with the information provided in "$PWD/yarn-error.log".
```

The trace tail looks like this:

```
Trace: 
  TypeError: Cannot read property 'length' of undefined
      at rows.map.row ($REPO/lib/reporters/console/console-reporter.js:87:68)
      at Array.map (native)
      at ConsoleReporter.table ($REPO/lib/reporters/console/console-reporter.js:87:27)
      at Object.<anonymous> ($REPO/lib/cli/commands/outdated.js:117:16)
```

After much console.log() debugging, I found that the `current` version used to generate the map key is inappropriate because it has been resolved to an exact version, whereas the `rootPatternsToOrigin` map was created with the normalized range found in the package.json. The actual error logged is due to passing `undefined` to `chalk.stripColor()`.

**Test plan**

``` sh
$ yarn outdated
yarn outdated v0.16.2
Package                   Current Wanted Latest Package Type
@financial-times/n-bottle 1.0.0   1.0.0  1.1.1  dependencies
✨  Done in 0.32s.
```

Unfortunately, there are no tests for the `outdated` command (WIP [here](https://github.com/yarnpkg/yarn/pull/1212), apparently). I'm willing to contribute to the WIP, but I'd rather not step on toes with this PR.

### CODE REVIEW

**Comment by wyze** [comment]
Thanks for the PR @evocateur. I finished up all the tests for `outdated`. Let's wait for them to merge and you can rebase this onto master and fix any failing tests or add a test to cover this case! 🎉

**Comment by evocateur** [comment]
Thanks, will do!

**Comment by evocateur** [comment]
I'll rebase this today and update the tests from #1212

**Comment by evocateur** [comment]
Rebased and added tests, this PR is ready to go. The CircleCI failure is unrelated, and seems to be affecting all runs on that platform since sometime earlier today.

**Comment by wyze** [comment]
Made redundant by #1696.

**Comment by evocateur** [comment]
@wyze Thanks!

**Pull request closed without merging**
