### PR TITLE
Switch to `path.join(...)` to get tests to pass in AppVeyor

### PR DESCRIPTION
**Pull request by jrop**
Quick bugfix/followup to yarnpkg/yarn/pull/3339.  See the comments for more details.

Switch to `path.join(...)` to get tests to pass in AppVeyor

**Test plan**

### CODE REVIEW

**Comment by bestander** [comment]
needs a rebase

**Comment by bestander** [comment]
I think only last commit is relevant

**Comment by bestander** [comment]
replaced with #3388, thanks and no worries

**Comment by jrop** [comment]
@bestander Thanks.  Been a busy morning at work; sorry for the half baked jobs

**Pull request closed without merging**
