### PR TITLE
Switch to micromatch: fixes yarnpkg/yarn#3336

### PR DESCRIPTION
**Pull request by jrop**
**Summary**

The micromatch library provides an inconsistent implementation of `.makeRe(...)` with the rest of it's interface.  It is known that `makeRe` does not produce Regular Expressions that can be trusted:

* isaacs/minimatch#67
* babel/babel#3914

This PR switches from minimatch => micromatch.

**Motivation**: #3336 😄 

**Test plan**

TODO:
* [x] Update tests and make them pass (before merge)

Tested so far:
```sh
$ alias my_yarn='node /github/yarn/lib/cli/index.js'
$ cd /my/other/project
$ my_yarn pack
$ tar -tf my-package-v1.0.0.tgz
#
# Output is as expected
#
```

### CODE REVIEW

**Comment by jrop** [comment]
Unpredictable tests on CircleCI fail with "timeout" errors:

```sh
Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at ontimeout (timers.js:386:14)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)
```

This failure does not seem to be related to this PR, am I correct?

**Comment by bestander** [comment]
Nice, thanks for a thorough explanation, tests and fix

**Comment by jrop** [comment]
@bestander 😰  I just realized that the way I added the extra test causes it to fail on windows in AppVeyor, because I hard coded the path separator `lib/a.js` for example.  On windows the test fails because the path will be `lib\a.js`.  I pushed one more commit that changes the test to use `path.join('lib', 'a.js')`.  Does it need another PR?

**Comment by bestander** [comment]
Yeah, could you send a new PR?

**Comment by bestander** [comment]
@jrop when to expect the PR?
I'd like to cut 0.25 release

**Comment by jrop** [comment]
@bestander Just submitted.  Sorry about that ☹️

**Comment by bestander** [comment]
no worries :)

**Pull request merged**
