### PR TITLE
removed entry.props.uid=0 for root after we switched from node-tar to tar-fs

### LINKED ISSUE #2866: yarn-e2e/label=docker,os=ubuntu-14.04 #123 failed
Build 'yarn-e2e/label=docker,os=ubuntu-14.04' is failing!

Last 50 lines of build output:

```
[...truncated 6.39 KB...]
Preparing to unpack .../ca-certificates_20160104ubuntu0.14.04.1_all.deb ...
Unpacking ca-certificates (20160104ubuntu0.14.04.1) ...
Selecting previously unselected package yarn.
Preparing to unpack .../yarn_0.23.0-20170308.0112-1_all.deb ...
Unpacking yarn (0.23.0-20170308.0112-1) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_6.10.0-1nodesource1~trusty1_amd64.deb ...
Unpacking nodejs (6.10.0-1nodesource1~trusty1) ...
Setting up openssl (1.0.1f-1ubuntu2.22) ...
Setting up ca-certificates (20160104ubuntu0.14.04.1) ...
Setting up yarn (0.23.0-20170308.0112-1) ...
Setting up nodejs (6.10.0-1nodesource1~trusty1) ...
Processing triggers for ca-certificates (20160104ubuntu0.14.04.1) ...
Updating certificates in /etc/ssl/certs... 173 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
+ ./run-yarn-test.sh
+ cd /tmp
+ mkdir yarntest
+ cd yarntest
+ echo '{}'
+ yarn --version
0.23.0-20170308.0112
+ rm -rf /root/.cache/yarn
+ yarn add react
yarn add v0.23.0-20170308.0112
info No lockfile found.
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
/usr/share/yarn/lib/fetchers/tarball-fetcher.js:141
        entry.props.uid = entry.uid = 0;
                        ^

TypeError: Cannot set property 'uid' of undefined
    at Extract.extractorStream.pipe.on.on.entry (/usr/share/yarn/lib/fetchers/tarball-fetcher.js:141:25)
    at emitThree (events.js:121:20)
    at Extract.emit (events.js:194:7)
    at Extract.onheader (/usr/share/yarn/node_modules/tar-stream/extract.js:177:10)
    at Extract._write (/usr/share/yarn/node_modules/tar-stream/extract.js:243:8)
    at doWrite (/usr/share/yarn/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/usr/share/yarn/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at Extract.Writable.write (/usr/share/yarn/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at UnpackStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
+ fail_with_log
+ exitcode=1
+ '[' -s yarn-error.log ']'
+ exit 1
Build step 'Execute shell' marked build as failure

```

Changes since last successful build:
- [bestander] d093c6cc1d2e28d906e0972b1d9a5ad5cd757bff - Move ROOT_USER to a separate file, fixes #2807 (#2855)

- [noreply] ddff4c5ae8f8ef65284746931c851cc642177816 - Refactored integrity generation and check (#2818)

- [noreply] 157a34aa5928792b596b1da99fc12027c9e00032 - switched to tar-fs from node-tar to unpack tars (#2826)

- [bestander] 2f49dcfe0119a960e28958679be15ace5c527ca3 - use process.mainModule.filename as npm_execpath (#2843)

- [bestander] 8ed57c0de6a8c29ac2f44a599cd39a6c2b7082f9 - Upgrade to flow v0.41.0 (#2862)

- [bestander] 2072978a0ffc2a65512e0336491485cce9bb6691 - Use release infra rather than ghr to create GitHub releases (#2839)

[View full output](https://build.dan.cx/job/yarn-e2e/label=docker,os=ubuntu-14.04/123/)

cc @Daniel15

### PR DESCRIPTION
**Pull request by bestander**
**Summary**

fixes #2866

**Test plan**

I don't know 100% what I am doing here, it should fix he NPE but not sure if a switch to tar-fs broke something related to #1837

@Daniel15, @lawliet89 is this fix enough?

### CODE REVIEW

**Comment by lawliet89** [comment]
I can't verify this until Monday. 

What I did in #1837 was work around `node-tar` which tries to `chown` everything it untars to the original `UID` and `GID` that was stored in the tarball when the user is `root`. This fails if your `root` user is behind a user namespace and the `GID` and `UID` is outside of its permissible range.

So this setting of `UID` and `GID` to zero might not be necessary if `tar-fs` doesn't try to do that (or this is a way to get it not to do that.

Sorry I'm not familiar with the shape of the objects in `tar-fs`.

**Comment by bestander** [comment]
Ok, I removed the root condition then, I pass dmode and fmode to tar-fs extraction, hopefully it means that access should be reset fine.
@lawliet89, would be great if you could verify this on Monday.

We probably should merge this PR because currently extraction fails for root users completely.

**Comment by lawliet89** [comment]
I just checked and both of your commits causes #1750 and friends to resurface, that is if your root user is inside a [user namespace](http://man7.org/linux/man-pages/man7/user_namespaces.7.html). 

```text
verbose 8.944 Error: https://registry.yarnpkg.com/immutable/-/immutable-3.8.1.tgz: EINVAL: invalid argument, chown '/usr/local/share/.cache/yarn/v1/npm-immutable-3.8.1-200807f11ab0f72710ea485542de088075f68cd2/contrib/cursor'
    at Error (native)

error An unexpected error occurred: "https://registry.yarnpkg.com/immutable/-/immutable-3.8.1.tgz: EINVAL: invalid argument, chown '/usr/local/share/.cache/yarn/v1/npm-immutable-3.8.1-200807f11ab0f72710ea485542de088075f68cd2/contrib/cursor'".

```

This fix works fine if you are not behind a user namespace, and I think it's correct because the entries themselves no longer have the `uid` or `gid` properties. They are now in the header.

The API for `tar-fs` allows us to [map the header](https://github.com/mafintosh/tar-fs/blob/master/index.js#L232) during extract. The header contains the `UID` and `GID`. I'll raise another PR to fix this.

**Comment by bestander** [comment]
Fixed by #2898

**Pull request closed without merging**
