### PR TITLE
Mock inquirer for all e2e tests

### LINKED ISSUE #2955: tests failing due to timeout errors
When running the test suite locally with the latest master, the following tests occasionally fail.

```
  ● install should respect --no-bin-links flag

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at ontimeout (timers.js:380:14)
      at tryOnTimeout (timers.js:244:5)
      at Timer.listOnTimeout (timers.js:214:5)

  ● should not loose dependencies when installing with --production

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at ontimeout (timers.js:380:14)
      at tryOnTimeout (timers.js:244:5)
      at Timer.listOnTimeout (timers.js:214:5)
```

I believe the second test should be "lose dependencies" as well.

### PR DESCRIPTION
**Pull request by bestander**
Fixes #2955, we don't want yarn to prompt during e2e installs

**Test plan**

CI should be green

### CODE REVIEW

**Comment by arcanis** [comment]
Shouldn't that be an error by default if Yarn asks for multiple versions in tests?

**Comment by bestander** [comment]
Appveyor tests are fixed with revert #2985

**Comment by bestander** [comment]
> Shouldn't that be an error by default if Yarn asks for multiple versions in tests?

There is definitely an inconsistency in tests caching implementation, we should tackle it sooner.
The tests sometimes go to remote servers to get package metadata but the committed caches in `__tests__/fixtures/request-cache` don't match the online data and inquirer gets invoked.

I'd just like to get tests green sooner

**Comment by arcanis** [comment]
👍

**Pull request merged**
