### PR TITLE
Add tests for command "run"

### PR DESCRIPTION
**Pull request by AlicanC**
See #821

### CODE REVIEW

**Comment by AlicanC** [comment]
@bestander tests are still failing on AppVeyor and Travis. TBH, I don't know what's going on. `yarn/npm test` works fine on my local.

I will come back and fix if I somehow figure out what's going on, but I'm stuck ATM.

**Comment by bestander** [comment]
Appveyor can be flaky at times.
But in this situation both Travis and Appveyor fail with the new run tests.
Could it be OS specific?
Circle runs on Linux

**Comment by wyze** [comment]
@AlicanC I just pulled this down and all the tests failed for me locally. I did rebase and push up to get it to run on CI, and it fails there as well. I suspect something isn't being mocked correctly.

**Comment by wyze** [comment]
Made redundant by #1788.

**Pull request closed without merging**
