### PR TITLE
Change global prefix directory to `/usr/local` on OS X

### LINKED ISSUE #1194: Location of global bin doesn't match the doc
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

```
$ brew install yarn
==> Downloading https://homebrew.bintray.com/bottles/yarn-0.15.1.el_capitan.bott
Already downloaded: /Users/work/Library/Caches/Homebrew/yarn-0.15.1.el_capitan.bottle.tar.gz
==> Pouring yarn-0.15.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/yarn/0.15.1: 5,239 files, 12.6M
$ yarn global bin
/usr/local/Cellar/node/6.8.1/bin
```

**What is the expected behavior?**

Shouldn't `yarn global bin` output `~/.yarn/bin` as per [the doc](https://yarnpkg.com/en/docs/install)?

**Please mention your node.js, yarn and operating system version.**

Node v6.8.1
yarn v0.15.1
Os X 10.11.6

### PR DESCRIPTION
**Pull request by KishanBagaria**
When node is installed from Homebrew, node exists at `/usr/local/Cellar/node/7.10.0/bin/node`

So yarn's global bin directory (`yarn global bin`) becomes: `/usr/local/Cellar/node/7.10.0/bin`

```
$ node -e 'console.log(process.execPath)'
/usr/local/Cellar/node/7.10.0/bin/node
$ yarn global bin
/usr/local/Cellar/node/7.10.0/bin
```

This creates two problems:

1. `/usr/local/Cellar/node/(version)/bin` is not present in `PATH` by default. Users have to modify their profile to extend `PATH` with `yarn global bin`.

2. When node is upgraded, all linked global binaries become inaccessible since `yarn global bin` automatically gets changed to `/usr/local/Cellar/node/(latest-version)` from `/usr/local/Cellar/node/(old-version)`. The global bin directory should remain constant on upgrades.

The fix is to simply use `/usr/local/bin` as the default global bin directory in OS X installations. NPM (`npm --global prefix`) also uses that directory (at least when installed from Homebrew).

This should also fix #1194.

**Alternatives**

1. Instead of all OS X installations, this change can be applied only to installations where node is installed from Homebrew, by checking if `process.execPath` begins with `/usr/local/Cellar`. Although, this issue would still be present with nvm or some other node-installer.

2. Instead of modifying yarn, a patch could be made in the [Yarn formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb) to automatically run `yarn config set prefix /usr/local`. (EDIT: It's not possible atm: https://github.com/Homebrew/homebrew-core/issues/7283#issuecomment-289795136) Other node-installers like nvm will also require similar changes.

3. In the `getGlobalPrefix` function, instead of
```
let prefix = path.dirname(path.dirname(process.execPath)); //=> /usr/local/Cellar/node/7.10.0
```
this could be used:
```
const whichNode = execa.sync('which', ['node']).stdout; //=> /usr/local/bin/node
let prefix = path.dirname(path.dirname(whichNode)); //=> /usr/local
```

### CODE REVIEW

**Comment by rally25rs** [comment]
I believe this PR would also fix: #2064

**Comment by KishanBagaria** [comment]
Didn't see that before, thanks.

It looks like some change related to this is required. The current behavior isn't preferred by everyone.

Do you know if the participants in that issue got notified of this PR when you mentioned it?

**Comment by bestander** [comment]
Looping in @Daniel15  as I completely lost faith in trying to understand all those prefixes needed for every OS

**Comment by Daniel15** [comment]
I'm not very familiar with Mac OS, but the issue on Linux would be that regular users normally don't have write access to `/usr/local`. My preferred fix here would be to use `/usr/local` if it's writable by the current user, otherwise use `~/.yarn/bin` or something similar.  

On Windows we always use a user directory: `%LOCALAPPDATA%\Yarn\bin` (eg. `C:\Users\Daniel\AppData\Local\Yarn\bin`)

**Comment by bestander** [comment]
To me it seems like a safe enough change for Mac OS, let's merge it.
Speak up if you want to revert it.

@KishanBagaria, you have expressed a few good ideas about paths in Linux.
Do you want to give it a try and help Yarn to provide a great experience with all those PATH problems?

**Comment by paulirish** [comment]
On Google corporate OS X machines `/usr/local` is owned by root, rather than the user. As a result, most Googlers with homebrew install to another location rather than only using homebrew via sudo (which is terrrible).

image

FWIW I've been manually adding my homebrew'd `node` path to `PATH` in order to make sure my yarn global installs work. [And I rev this each time I upgrade node. It's kinda gross. :/](https://github.com/paulirish/dotfiles/blob/6fbe3da9b16cc48511eceab38be407daca0f499b/fish/path.fish#L26-L43)

For me, it'd be perfect to install the global links into `~.yarn/bin`  (as I've expected them to be there multiple times).  @Daniel15's proposal of falling back to there if `/usr/local` isn't writable is fine with me.

**Comment by bestander** [comment]
Thanks for feedback @paulirish.
I'll revert this now.

@KishanBagaria would you give it another try with @Daniel15's feedback?

**Comment by KishanBagaria** [comment]
@paulirish That must needlessly require sudo for a lot of install scripts. Maybe you should drop the suggestion of making `/usr/local` user-accessible in their issue tracker.

Until the next Yarn release, you can simply run `yarn config set prefix ~/.yarn` and get rid of the hacks in your dotfile.

**Pull request merged**
