### PR TITLE
Only compare root domains to determine authentication

### PR DESCRIPTION
**Pull request by karl-run**
Possible fix for #5429, if comparing root domains is sufficient.

### CODE REVIEW

**Comment by arcanis** [comment]
I'm not sure I like this ... we can imagine a registry service using subdomains to split their users instances :/

**Comment by karl-run** [comment]
I do agree, even though that sounds like a very rare case. Any idea on how npm handles this?

**Comment by karl-run** [comment]
Also this implementation won't work on domains such as co.uk.

Anyway, would it be sufficient to first check for the specific host, and then also check on the root domain? That would work in both cases.

**Comment by karl-run** [comment]
On further inspection this is garbage.

**Pull request closed without merging**
