### PR TITLE
fix: small typo in why command messages

### PR DESCRIPTION
**Pull request by sherwino**
**Summary**

This is not a feature request.

When running `yarn why` note that there is a small typo in step 2/4:

```
[2/4] Initialising dependency graph...
```

This PR just briefly corrects the text to be: `Initializing`
Also sent a PR to update the docs https://github.com/yarnpkg/website/pull/1032

**Test plan**

I believe this change does not need to be tested, it is just a change to the message.

### CODE REVIEW

**Comment by Daniel15** [comment]
They're both correct... Initialising is the British English spelling, while Initializing is the American English spelling 😛 

Not sure if Yarn is consistently using either British or American English...

**Comment by sherwino** [comment]
Thanks @Daniel15 you are right.

I didn't consider the international / UK spelling of the word, I'll keep that in mind whenever I make a language based PR.

I'll be consistent with the rest of the content / copy. 

Please note that the team maintaining the docs site merged my PR

https://github.com/yarnpkg/website/pull/1032

Let me know if that should be changed.

**Comment by olingern** [comment]
@arcanis since this was merged on the docs, I guess it's fine to merge here.

**Comment by sherwino** [comment]
Closing.

**Pull request closed without merging**
