### PR TITLE
[CI] enabled package-resolver tests

### PR DESCRIPTION
**Pull request by bestander**
**Summary**

Enabled most packager-resolver tests.
Npm-ml tests needs to be either replaced by others or fixed.

### CODE REVIEW

**Comment by bestander** [comment]
Hm, looks like resolver tests on Windows get broken.

**Comment by mourner** [comment]
@bestander Any reason not to merge this now that the tests are passing?

**Comment by bestander** [comment]
Just waiting for peer review :)
Would you check it? I'll merge it then

**Comment by mourner** [comment]
@bestander it's certainly an improvement, so 👍 on merging.

**Pull request merged**
