### PR TITLE
Added yarn install to circle.yml

### PR DESCRIPTION
**Pull request by bestander**

### CODE REVIEW

**Comment by bestander** [comment]
failed because of https://github.com/yarnpkg/yarn/issues/1142

**Comment by danez** [comment]
Another workaround would be to install node-legacy which basically is doing the symlink, see https://github.com/nodejs/node-v0.x-archive/issues/3911#issuecomment-18951288

**Comment by bestander** [comment]
I think I got some reasonable compormise :)

**Comment by bestander** [comment]
@cpojer virtually stamped it

**Comment by Daniel15** [comment]
Hmm, CircleCI should have Node.js installed via apt-get and so /usr/bin/nodejs should exist. Does it not?

**Comment by bestander** [comment]
Circle installs node here: /opt/circleci/nodejs/v6.8.1/bin/node.
It looks like `nvm` script is used so I don't think it uses debian package manager to isntall node.
We don't have permissions to do `ln -s /usr/bin/nodejs /usr/bin/node` or something similar

**Pull request merged**
