### PR TITLE
Fix offline resolution

### PR DESCRIPTION
**Pull request by arcanis**
**Summary**

Fix #3221

### CODE REVIEW

**Comment by bestander** [comment]
A test with absolute unix path would be awesome ;)

**Comment by arcanis** [comment]
@bestander How would you do it? Adding a marker like `%%PATH%%` somewhere in the `package.json` file from the fixture, and replacing it at runtime from within the test?

**Comment by bestander** [comment]
This is the example from create-react-app:
yarn add /path/create-react-app/packages/react-scripts/react-scripts-0.9.4.tgz

**Comment by bestander** [comment]
Also replacing path in yarn.lock during test could work

**Pull request merged**
