### PR TITLE
Don't use .includes for compatibility with Node 4

### PR DESCRIPTION
**Pull request by Volune**
**Summary**

Several tests fail on Node 4 because of the use of `Array.prototype.includes`

**Test plan**

Existing tests on Node 4

### CODE REVIEW

**Comment by bestander** [comment]
So did we stop transpiling ES6 correctly ?
I think we should fix the build tool to include proper shim rather than limit people in language.

**Comment by Volune** [comment]
I would agree, but that's not the solution that was chosen in #3592 and #3654
Should we add a dependency to `babel-polyfill` ?

**Comment by bestander** [comment]
I think those PRs we just agreed on a quick fix.
People keep using ES6 so it breaks all the time.

Does babel-polyfil fix the problem?

**Comment by bestander** [comment]
Opened an issue https://github.com/yarnpkg/yarn/issues/3693 to track the problem.

**Comment by bestander** [comment]
Thanks for raising this, @Volune.

**Pull request closed without merging**
