### PR TITLE
Atomic node modules

### PR DESCRIPTION
**Pull request by Xion**
**Summary**
This PR adds the `--atomic` flag.

When invoked with the `--atomic` flag, Yarn will temporarily rename the node_modules directory and install all packages within this new destination, only to rename it back at the end.

In a sense, this makes the `yarn install` operation "atomic", because anything that watches node_modules for changes will not see its intermediate state. This is useful to prevent processes like Watchman from taking action based on incomplete installation state.

**Test plan**
Tests included in the PR.

### CODE REVIEW

**Comment by rally25rs** [comment]
Seems like a good idea. Well thought out. Good tests.
Needs some merge conflicts resolved, but otherwise 👍

**Comment by BYK** [comment]
@Xion  - Still working on this?

@bestander, @arcanis any thoughts?

**Comment by bestander** [comment]
I think the PR is great, thanks again for the contribution @Xion and really sorry for leaving it unattended for a while.

I'll leave it to @BYK to make do the review and follow up with the rebase.

**Comment by BYK** [comment]
@Xion - up for rebasing?

**Comment by Xion** [comment]
Yep, I'll rebase & resolve the conflicts.

**Comment by Xion** [comment]
The CI uses an ancient version of Node which doesn't have `Object.values`. I'll shim it.

**Comment by Xion** [comment]
Looks like it's good to go!

**Comment by BYK** [comment]
>The CI uses an ancient version of Node which doesn't have Object.values. I'll shim it.

The CI uses Node 4 and 6 now which are the versions we commit to support :) Node 8 will be there soon. Thanks for fixing it!

**Comment by BYK** [comment]
I am going to go ahead and close this PR. Although it breaks my heart, I do not think it is worth having the additional code and complexity around this feature for the potential benefits of it.

If anyone disagrees with me, please feel free to keep the discussion open and ask for reopening this PR.

**Pull request closed without merging**
