### PR TITLE
Fix: Don't assume all string configs are paths

### PR DESCRIPTION
**Pull request by BYK**
**Summary**

Refs #3787. When reading from the config, it was assumed that all string values are possible paths unless explicitly stated causing the `~` semver modifier to be expanded to user's home path if it was set as `save-prefix`. This patch makes `expand` default to false.

**Test plan**

Added a new test case for this specific scenario.

### CODE REVIEW

**Comment by arcanis** [comment]
Ooooh I see - the regex doesn't take into account the case where the tilde is the only character in the string. I feel like this should be fixed into the regex rather than the code, wdyt? Only a matter of replacing the lookahead by a capture group.

**Comment by BYK** [comment]
@arcanis  - There's no regex, this is done here: `https://github.com/yarnpkg/yarn/pull/3941/files#diff-9d9a6cd82f41984872a66a3ab0d440c4R197`.

If you're referring to the regex in `expandPath`, I disagree. `~` should be expanded. The problem is on the config reading part which assumes any string value is a path and I've fixed exactly that :)

**Comment by arcanis** [comment]
> If you're referring to the regex in expandPath, I disagree. ~ should be expanded.

Why that? If someone needs to expand it, they can use `~/` to avoid the ambiguity. I'm just a bit wary of adding a per-option behavior when we could have a consistent behavior everywhere.

**Comment by BYK** [comment]
>Why that? If someone needs to expand it, they can use "~/" instead to avoid the ambiguity.

This puts the onus on the users instead of us, the tool providers. Since it would create a surprising behavior, I don't think that's a good idea.

>I'm just a bit wary of adding a per-option behavior when we could have a consistent behavior everywhere - especially if we have to take care of passing the right arguments to getOption everytime.

We already had this and I made the lightest change I could do to not make things worse. That said if you want, you can remove the boolean argument and add the `expandPath` calls where they need to be used in a follow-up. Alternatively, we can add "option types" and separate "path" types from "string" types but that sounds a bit heavy-handed to me for now.

**Pull request merged**
