### PR TITLE
Selective versions resolutions

### PR DESCRIPTION
**Pull request by victornoel**
**Summary**

This is an implementation for yarnpkg/rfcs#68.

For now there is only failing tests to start things up. I'm not sure I will be able to implement it so at least I will provide the tests for someone more knowledgeable of yarn codebase to focus on the implementation itself :)

@bestander @arcanis 

**Test plan**

There was an RFC made and discussed.
We should at least add those unit tests:
 - [ ] non-exact versioning
  - I'm not sure how to do that if I am to use local file-based dependencies
 - [ ] previously flattened project
 - [ ] ...

### CODE REVIEW

**Comment by bestander** [comment]
Great start, @victornoel.
Would be so great to get you involved in implementation.
What can I do to motivate you? :)

It is a good idea to start with tests, make them skipped once you are happy that you the coverage is good and we'll merge it to make the PR not stalling.
In the next iteration someone could implement the actual fix to package-resolver

**Comment by BYK** [comment]
@victornoel hi! Need anything from us?

**Comment by victornoel** [comment]
@BYK sorry, I have been a bit under the water lately and I will be AFK for a month, so it's either on hold or someone else can start working on it :)

I won't handle the implementation though, so if someone is interested, it's possible to start from the existing acceptance tests and the RFC. If not, I will try to make more acceptance tests in a month.

**Comment by BYK** [comment]
>@BYK sorry, I have been a bit under the water lately and I will be AFK for a month, so it's either on hold or someone else can start working on it :)

No worries, thanks for the update :) I think @kaylieEB is on this now.

**Comment by BYK** [comment]
Closing this in favor of #4105. LMK if you think that's a mistake.

**Pull request closed without merging**
