### PR TITLE
Update to CircleCI 2.0

### PR DESCRIPTION
**Pull request by charpeni**
Related to #2933.

**Summary**

Update CircleCI config to support 2.0.

I'm not sure about the webhooks part, it doesn't seem supported from `config.yml` in 2.0.

**Test Plan**

In my own CircleCI project

### CODE REVIEW

**Comment by Daniel15** [comment]
I've already got a work-in-progress `circleci.yml` file in the `circleci-2` branch: https://github.com/yarnpkg/yarn/commit/45822ca6054308621d2108e3f6a48f283a3cbe11. What does this one do differently? I did see that it includes deployment (which is missing from my one), but is anything else different?

The version I was playing with had an issue where the build would be marked as successful even when tests fail. Does this have the same problem? Could you try intentionally failing a test and see if it correctly marks the build as failed?

**Comment by charpeni** [comment]
I had seen your branch, I was interested in knowing why your builds fail, but is still showing green.

So I look up at the config from your branch and it seems a bit outdated from the latest [CircleCI documentation](https://circleci.com/docs/2.0/language-javascript/). so I've decided to give it a shot.

I do not have the same issue as your branch as you can see my commit is failing all CI tests due to a timeout and it shown red on CircleCI.

The whole upgraded configuration seems right now, but i'm not sure about the webhooks part.

If I can do anything to help you, it will be a pleasure.

**Comment by Daniel15** [comment]
Sorry I haven't had a chance to look at this yet! Most likely I'll copy your configuration and tweak it a bit, as we've performed some changes to the CircleCI config in the meantime. Thanks for looking into it 😃

**Comment by bestander** [comment]
Hey @charpeni!
Thanks for spending time on this one and sorry for a delay.

What do you think we should do next?
If 2.0 is better than 1.0 then let's rebase and merge if it satisfies all our CI needs.

**Comment by bestander** [comment]
Otherwise let's close it :)

**Comment by BYK** [comment]
@charpeni - Still interested in moving forward with this? I'd love for us to stay up to date with CircleCI so really appreciate your effort.

**Comment by charpeni** [comment]
I'll rebase this PR in the next couple of days and check for the missing webhooks part.

**Comment by BYK** [comment]
Thanks a lot! Feel free to ping me directly if you need anything from our side.

**Comment by Daniel15** [comment]
I'm going to update the Docker container as the current one is getting a bit outdated (although the current one still works fine).

Let's split building, testing, and packaging into three separate workflows: https://circleci.com/docs/2.0/workflows/

**Comment by Daniel15** [comment]
Now that CircleCI 2.0 is public, there's a useful migration document: https://circleci.com/docs/2.0/migrating-from-1-2/

**Comment by BYK** [comment]
@Daniel15 @charpeni need any help or nudge? :D

**Comment by Daniel15** [comment]
Continued in #4271

**Pull request closed without merging**
