### PR TITLE
Add package path to json list

### PR DESCRIPTION
**Pull request by krzysztof-pawlik-gat**
**Summary**

`licensed` tool for auditing licenses of packages needs to have a directory where a package is installed. Right now even for applications using `yarn` it will fallback to using `npm` to list dependencies, to fix that `yarn` needs to output a directory where files for each package are available.

**Test plan**

Tests have been updated, the only tricky part was that each test run will generate a different path (due to using `/tmp` and one-time directories in it), hence special care had to be taken to account for this.

### CODE REVIEW

**Comment by krzysztof-pawlik-gat** [comment]
Tests will be failing due to expired certificates until #7457 is merged.

**Comment by rockwyc992** [comment]
@krzysztof-pawlik-gat #7457 has been merged, could you update `CHANGELOG.md` again?

**Comment by krzysztof-pawlik-gat** [comment]
@rockwyc992 thanks! I've updated `CHANGELOG.md` and updated tests so they don't fail on Windows. All checks passing.

**Comment by krzysztof-pawlik-gat** [comment]
Lint seems to be failing on master since #7512 got merged.

**Comment by krzysztof-pawlik-gat** [comment]
Windows Node 10 failed with:

```
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.3.3.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "d:\\a\\1\\s\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn run v1.17.3
$ gulp build
[‌06:19:15‌] Local modules not found in d:\a\1\s‌
[‌06:19:15‌] Try running: npm install‌
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
bin:
total 12K
-rwxr-xr-x 1 VssAdministrator 197121 1.1K Sep 19 06:12 yarn
-rw-r--r-- 1 VssAdministrator 197121   34 Sep 19 06:12 yarn.cmd
-rwxr-xr-x 1 VssAdministrator 197121 1015 Sep 19 06:12 yarn.js
-rw-r--r-- 1 VssAdministrator 197121  175 Sep 19 06:12 yarn.ps1
-rwxr-xr-x 1 VssAdministrator 197121   42 Sep 19 06:12 yarnpkg
-rw-r--r-- 1 VssAdministrator 197121   30 Sep 19 06:12 yarnpkg.cmd
ls: cannot access 'lib': No such file or directory
##[error]Bash exited with code '2'.
```

The rest of tests/builds looks OK.

**Comment by sergey-alekseev** [comment]
Waiting for this as well to be able to use licensed for yarn.

**Pull request closed without merging**
