### PR TITLE
Fix pack includes files from `node_modules`, closes #2047

### LINKED ISSUE #2047: `yarn pack` includes files from `node_modules`
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Using `yarn pack` includes `readme`, `changelog` and `package.json` from `node_modules`. Probably the files forcibly included: https://github.com/yarnpkg/yarn/blob/1e7249966890c22df0c1564660a21a54ce17370b/src/cli/commands/pack.js#L44-L47.

**If the current behavior is a bug, please provide the steps to reproduce.**

See https://github.com/yarnpkg/yarn/issues/761#issuecomment-263112301.

`mkdir some-dir && cd some-dir && yarn init -y && yarn add object.entries && yarn pack && tar -ztvf some-dir-v1.0.0.tgz`

**What is the expected behavior?**
That `node_modules` is ignored entirely

**Please mention your node.js, yarn and operating system version.**
Node@6.9.1, Yarn@0.17.9, macOS Sierra

### PR DESCRIPTION
**Pull request by torifat**
**Summary**
- Only look for mandetory files (`package.json`, `readme`, `license`, etc) in root
- Stop `fs.walk` inside ignored dirs (`node_modules`, `.git`, `.svn`, etc), makes `pack` way faster

**Test plan**

With only `webpack` dependency:

**before**
```
 ❯ yarn pack
Alias tip: y pack
yarn pack v0.17.8
warning package.json: No license field
success Wrote tarball to "/Users/rifat/Developments/test/yarn/yarn-test-v1.0.0.tgz".
✨  Done in 12.54s.
```

**after**
```
 ❯ yarn-dev pack
Alias tip: yd pack
yarn pack v0.18.0-0
warning package.json: No license field
success Wrote tarball to "/Users/rifat/Developments/test/yarn/yarn-test-v1.0.0.tgz".
✨  Done in 0.08s.
```

### CODE REVIEW

**Comment by bestander** [comment]
@torifat, any idea why the pack test failed on Travis but not on others?

**Comment by torifat** [comment]
@bestander Same as this one: https://github.com/yarnpkg/yarn/blob/master/__tests__/commands/pack.js#L104

I will try to figure it out.

**Comment by torifat** [comment]
@bestander I have figured it out.

**Comment by SimenB** [comment]
Sneaking in a thank you to @torifat for introducing me to https://github.com/djui/alias-tips, not I can finally learn more of oh-my-zsh's git aliases :D

**Pull request merged**
