### PR TITLE
Breaking: Remove unsupported aliases

### LINKED ISSUE #3892: Remove every unsupported-alias
We should remove every unsupported-alias (https://github.com/yarnpkg/yarn/blob/master/src/cli/unsupported-aliases.js) from the codebase.

### PR DESCRIPTION
**Pull request by onurtemizkan**
**Summary**
Resolves #3892

**Test plan**
I removed `unsupported-aliases` tests too

### CODE REVIEW

**Comment by BYK** [comment]
According to CircleCI you missed some tests :)

You can run tests locally by running `yarn build; yarn test`

**Comment by BYK** [comment]
@voxsim I labeled this as "breaking". Do you agree?

**Comment by voxsim** [comment]
@BYK yes, in some sense is a breaking change ;)

**Comment by voxsim** [comment]
Thanks @onurtemizkan !! I will merge it :)

**Pull request merged**
