### PR TITLE
Disables by default the migrations

### PR DESCRIPTION
**Pull request by arcanis**
**Summary**

While not breaking technically speaking, the automatic migration is causing unexpected behaviors to our users. Such a behavior should only happen when bumping the major version.

To prevent that, the `unsafe-disable-integrity-migration` settings will default to `true` for the duration of the 1.X branch. **It will default to `false` again starting with the 2.0.**

In order to migrate your project now, just add the following line into your project-local yarnrc:

```
unsafe-disable-integrity-migration "false"
```

Note that this only affect the lockfile entries already present in your lockfile. Yarn will continue to create the new entries using the `integrity` field. My guess is that by the time the 2.0 lands, enough projects will have been migrated to use the `integrity` field that this will be a painless transition.

**Test plan**

CI

### CODE REVIEW

**Comment by arcanis** [comment]
> What do you think about adding a warning message that would explain this to the user (or link to a help page with more details)?

Not sure - should we print the warning every time? It would be very verbose (especially if it includes a link). It sounds like the kind of thing that users will just ignore since "it works".

**Comment by Gudahtt** [comment]
I would suggest that the option could be renamed to avoid the double-negative, but then the `unsafe-` prefix ceases to make sense. We don't want to imply that migrations are unsafe.

I don't think printing a warning each time is warranted - there is nothing actionable here for the user to do.

**Comment by arcanis** [comment]
Yep, the double negation was because I preferred to make it explicit that we recommend this option not to be turned on (a bit like [`DO_NOT_USE_OR_YOU_WILL_BE_FIRED`](https://github.com/facebook/react/blob/80bff5397bf854750dbe7c286f61654ea58938c5/src/umd/ReactUMDEntry.js#L21-L22)).

**Comment by imsnif** [comment]
A message each time might indeed be excessive. Maybe some documentation somewhere like here then? https://yarnpkg.com/lang/en/docs/yarnrc/

**Comment by arcanis** [comment]
@imsnif Do you have an idea why the bailout tests are failing?

**Comment by imsnif** [comment]
@arcanis - my guess would be something to do with https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/install.js#L465
But I'll have to take a closer look. Can do later tonight if it can wait.

**Comment by arcanis** [comment]
> Making a third, hybrid format lockfile that has only some integrity entries is no use to 1.10 users because it doesn't really check the integrity

Yarn will check the integrity. It just will keep using the sha1 for old ones. The main reason we've disabled the migration by default is that the lockfile should not change when you run `yarn install` on an up-to-date project, except between major releases.

**Comment by borekb** [comment]
A bit OT but since we're fighting this integrity field in our team where not everyone is on the same Yarn version (I know...), is there a way to pass `unsafe-disable-integrity-migration` from the command-line?

**Comment by rjmunro** [comment]
@arcanis I'm seeing random integrity entires being added, depending on who / where yarn is being run, then being removed again when someone on an old version runs it. These all go into version control. It's a total mess. There should only ever be all or no entries. Which state a particular lock file is in should be left alone unless the user changes it (e.g. by running something like a special command, maybe `yarn upgrade-lockfile`).

**Comment by arcanis** [comment]
@borekb @rjmunro this doesn't entirely answer your question, but are you aware that you can very easily force all of your team to use the exact version of Yarn you want them to use?

Just create a `.yarnrc` in your repositories, add `yarn-path "./scripts/yarn-1.12.1.js"` inside, add the [single-file release](https://github.com/yarnpkg/yarn/releases/tag/v1.12.1) to the right place, commit all this, and voilà. As long as your developers have Yarn 1.0 globally installed (which is more than one year old), Yarn will transparently use the version you've selected over the global one 🙂 

We use this pattern at work and it's extremely handy to force everyone to upgrade at once, or to rollback everyone if we find a regression.

**Comment by borekb** [comment]
@arcanis That is a clever trick, thank you!

**Pull request merged**
