### PR TITLE
Delete eslint-plugin-prettify and revert back to custom scripts for prettier

### PR DESCRIPTION
**Pull request by voxsim**
Please see the discussion in https://github.com/yarnpkg/yarn/pull/3401.

cc @bestander

### CODE REVIEW

**Comment by bestander** [comment]
I thought it was a small patch, is 150 files change required?

**Comment by voxsim** [comment]
Mmh maybe if i set the print width to 120, it will reduce the file changes, I let you know later

**Comment by voxsim** [comment]
ok I was right :)

**Comment by bestander** [comment]
Thanks a lot for the contribution, @voxsim!
Hoping to get a proper fix :)

**Pull request merged**
