### PR TITLE
Fix yarn pack command for scoped packages, fixes #1714

### LINKED ISSUE #1714: ENOENT packing a scoped package
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you want to `yarn pack` a scoped package, you will get an 

```
Error: ENOENT: no such file or directory, open 'D:\XXX\.build\@scope\package.tgz'
    at Error (native)
events.js:160
      throw er; // Unhandled 'error' event
      ^
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a scoped package. E.g. `"name": "@scope/package"` and run `yarn pack`

**What is the expected behavior?**
It should pack a .tgz... somehow... :)

**Please mention your node.js, yarn and operating system version.**
node v6.9.1
yarn v0.16.1
Win7 x64 (regardless whether in cmd, git-bash, etc)

### PR DESCRIPTION
**Pull request by KidkArolis**
Similar to

https://github.com/npm/npm/blob/6f34aa2d366fc9f90ae0d500ef980dd6c4ce505c/lib/pack.js#L54-L55

Verified by creating `package.json` with name `@some/scope` and running `yarn pack`. This command didn't seem to have any tests yet :-"

### CODE REVIEW

**Comment by KidkArolis** [comment]
Lemme guess, I should add a test :)

**Comment by bestander** [comment]
@KidkArolis you got it right.
There are tests added in https://github.com/yarnpkg/yarn/pull/1464, I had to revert it though because of lint issues and code changes.

**Comment by garthk** [comment]
@bestander, requesting more tests seems to have inflicted a 39 day delay on progress with this ticket. If @KidkArolis isn't up to making sufficient tests in a timely manner, might I suggest you accept the PR and add your own tests so `yarn pack` can work with scoped packages?

**Comment by garthk** [comment]
Also pinging @t-obi and @torifat, as both have contributed significant changes to `pack` and hopefully have enough experience with its tests to fast-track a fix.

**Comment by t-obi** [comment]
hey, I had a quick look at this and I could add some tests if that's ok for everyone. I have a basic test setup already, just some small problems to fix.

**Comment by bestander** [comment]
@t-obi, go for it please.
@garthk, I'll wait till tomorrow and then merge this one

**Comment by bestander** [comment]
Merging this and releasing 0.19 today.
A follow up PR with tests will be greatly appreciated.

**Pull request merged**
