### PR TITLE
Fix `yarn outdated` for scoped packages (#620)

### PR DESCRIPTION
**Pull request by jsynowiec**
**Summary**

`yarn outdated` command throws an error due to NPM registry returning 404 HTTP error code for scoped packages. See #620, #709, #651, #983, #1126, #1181

Package name must be escaped when querying NPM registry.

#1071 fixes this but by manually replacing `/` with escape sequence. A better solution is to use the `escapeName` static method directly in the `NpmRegistry` class.

**Test plan**
1. Create an empty project, add package.json file,
2. Run `yarn add @types/node@6.0.40`
3. Run `yarn outdated`

screenshot 2016-10-19 23 07 54

### CODE REVIEW

**Comment by donpark** [comment]
Something else besides character escaping issue is going on.

With version v0.16.0, `yarn outdated` throws `@types/blah not found` error although `@types/blah` is installed. Executing redundant `yarn add @types/blah` succeeds and `yarn outdated` executed again this throws `@types/foobar not found` error. Repeating this eventually loops back to `@types/blah not found` error. Bizarre to say the least.

**Comment by jsynowiec** [comment]
@donpark please, clone my [fix/outdated-cmd-for-scoped-packages](https://github.com/jsynowiec/yarn/tree/fix/outdated-cmd-for-scoped-packages) branch, [setup and build](https://github.com/yarnpkg/yarn/blob/master/CONTRIBUTING.md#setup) the project and then repeat your test using the built yarn from `bin/yarn`. 
I'm unable to reproduce what you've described. Also, let's move this conversation to #620 issue so all comments here are related to the PR.

**Comment by donpark** [comment]
@jsynowiec yup. yarn built from your branch fixed the problem. so the erratic behavior I saw was a side-effect of the bug you fixed. awesome. looking forward to seeing this fix published ASAP.

**Comment by dylanparry** [comment]
I've closed #1071 in favour of this fix as it does it in a much better way.

**Comment by camjc** [comment]
Are we doing a release soon? This fix is a blocker for a lot of people and has been merged for 10 days already.

**Comment by donpark** [comment]
I too expected a quick release as scoped modules are required for TypeScript projects. Is yarn release policy/schedule documented anywhere?

**Pull request merged**
