### PR TITLE
Fix local mirror invalid file name (#4076)

### PR DESCRIPTION
**Pull request by jespino**
There is a problem related to how url.parse and path.basename is used to build the repository name. So the simplest and easiest solution to this, is after the parsing remove ":" when is needed. Looks quick and dirty but understanding that the objective of the function is to transform reference to the packageFilename looks like the correct place to manage exceptional behavior.

### CODE REVIEW

**Comment by arcanis** [comment]
Thanks for your help! Can you give an example of something that demonstrates the issue, and write a test in the `__tests__` folder to make sure we don't unexpectedly have a regression later on?

**Comment by jespino** [comment]
Hi @arcanis , the demonstration process is in the issue #4076 (you can follow the issue steps and you get a cache file that starts with ":" which is an invalid character in windows).

About the test, of course, I'll add a test for it.

**Comment by jespino** [comment]
Added the new test, this check that the generated cache directory doesn't include the ":" in this especial case.

**Comment by arcanis** [comment]
Thanks! 👍

**Pull request merged**
