### PR TITLE
fix audit for packages without name

### PR DESCRIPTION
**Pull request by bugzpodder**
Fixes https://github.com/yarnpkg/yarn/issues/6607#issuecomment-434855932

### CODE REVIEW

**Comment by arcanis** [comment]
Now that's interesting - how come some packages have no name ? 😮

**Comment by rally25rs** [comment]
If they don't have a `name` then we should probably omit them from the audit contents at all, since npm isn't going to have issues listed for a package with no name anyway. I think we should just skip it when building the audit tree.

**Comment by bugzpodder** [comment]
@rally25rs the main package is a private package (not published) and it doesn't have a name, however its dependencies should still be checked.

**Comment by bugzpodder** [comment]
See for example: https://github.com/yarnpkg/yarn/issues/6607#issuecomment-434870068

**Comment by gabegorelick** [comment]
This does not appear to fix #6607. I still get that error even after applying this patch.

**Comment by bugzpodder** [comment]
@gabegorelick It most definitely fixes https://github.com/yarnpkg/yarn/issues/6607#issuecomment-434870068 
But I understand you have have a different problem.  However we can't help you unless there is a repro case.

**Comment by bugzpodder** [comment]
`$ yarn audit
yarn audit v1.12.1
error An unexpected error occurred: "Unexpected audit response (Missing Metadata): false".
info If you think this is a bug, please open a bug report with the information provided in ".../yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/audit for documentation about this command.
$ yarn-local audit
yarn audit v1.13.0-0
0 vulnerabilities found - Packages audited: 37909
✨  Done in 2.56s.`

**Comment by gabegorelick** [comment]
@bugzpodder My apologies. In posting a minimal repo case for #6607, it seems I got too minimal in dropping the `name` field from package.json and discovered another bug :)

**Comment by arcanis** [comment]
The problem comes from empty `dependencies` fields (cf https://github.com/yarnpkg/yarn/issues/6607#issuecomment-434875058).

@bugzpodder, do you mind also fixing it in the same PR? It should just be a change in `_mapHoistedTreesToAuditTree` (something like transforming empty dependency fields to `*` should do the trick).

**Comment by arcanis** [comment]
Perfect, thanks!

**Pull request merged**
