### PR TITLE
improved error message

### PR DESCRIPTION
**Pull request by bestander**
**Summary**

Something like "Bad hash. Expected X but got Y" is not really useful when debugging.
This PR changes the error message to include the file name.

** Test **

```
<break a sha1 in one of the dependencies>
yarn install v0.24.0-0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error Hashes don't match when extracting file "JSONStream-1.2.1.tgz". Expected "12aa5790e799481083b49b4b7fa94e23bae69bf9" but got "32aa5790e799481083b49b4b7fa94e23bae69bf9"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

The snapshot test for some reason has `<url>:` error message format but in real application the `<url>:` gets dropped

### CODE REVIEW

**Comment by szarouski** [comment]
While this PR is not merged, is there a way to find out what is triggering Bad hash error? Thank you.

**Comment by bestander** [comment]
Find the hash in yarn.lock

**Comment by szarouski** [comment]
In my case yarn.lock is not even created. I'll keep searching, thanks for your help.

**Comment by bestander** [comment]
@szarouski then run `yarn install --verbose`, it will print all the GET request

**Pull request merged**
