### PR TITLE
Fix: always output reporter.inspect values and `config get` result

### LINKED ISSUE #3922: Yarn config is empty when run from within an npm script
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The output of `yarn config` is empty if run from within a yarn script.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create an empty project with a script in `package.json`: 
```
"scripts": {
    "debug": "yarn config list"
}
```
2. Run the script with `yarn run debug`.

**What is the expected behavior?**

Expect `yarn run debug` to produce the same output as `npm run debug` or `yarn config list`.

**Please mention your node.js, yarn and operating system version.**
node.js v6.11.0
yarn v0.27.5
OS Ubuntu 16.04

Seems this was introduced sometime between v0.24.5 and v0.27.5. We were using this behavior as part of a docker build script that would internally grab an NPM authorization token (from `yarn config`) to provide it to the docker container being built. Would be nice to see the regression fixed, to bring this back into line with npm's behavior.

### PR DESCRIPTION
**Pull request by BYK**
**Summary**

Fixes #3922. Certain commands in yarn should always produce an
output, regardless of the silent status. This makes
`reporter.inspect` for console reporter to always produce an
output. It also forces the output of `yarn config get` to override
silent mode.

**Test plan**

Should add integration tests.

### CODE REVIEW

**Comment by BYK** [comment]
@kaylieEB I think you were referring to `this.log('' + value, {force: true});`. I changed it to use `String()` instead for explicit string casting.

**Comment by kaylieEB** [comment]
Sorry I was referring to using template literals ``` `${value}` ```, but this already looks good to merge :).

**Comment by BYK** [comment]
>Sorry I was referring to using template literals `${value}`, but this already looks good to merge :).

That is still implicit string conversion. I opted for the explicit `String()` one :) We should probably enable https://eslint.org/docs/rules/no-implicit-coercion in our code base.

**Comment by kaylieEB** [comment]
interesting, i was suggesting it more for readability but being explicit makes better sense, thanks :)

**Pull request merged**
