### PR TITLE
fix broken link

### PR DESCRIPTION
**Pull request by seongahjo**
**Summary**

fix broken link for contributing

**Test plan**

### CODE REVIEW

**Comment by arcanis** [comment]
@seongahjo Which broken page are you redirected to? I'm redirected to the `/en/` version, so if you have a broken page maybe it's because we don't have the page in your language yet!

**Comment by seongahjo** [comment]
@arcanis It doesn't redirect to any other page, just shows 404 Page. below is the 404 page.
But other links, such as 'Installation Guide' or 'Usage Guide' work fine, their <a> tag link to /en/ version.
I think if 'Contributing' does same job for unsupported languages, it will be better.
capture

**Comment by kaylieEB** [comment]
Hi @seongahjo , thanks for the PR! I'm able to reach the link without an issue, would you mind verifying it again?
screen shot 2017-11-26 at 11 04 21 am

**Comment by kaylieEB** [comment]
closing this in favor of https://github.com/yarnpkg/website/issues/385

**Pull request closed without merging**
