### PR TITLE
Add public repository hint for issue creators

### PR DESCRIPTION
**Pull request by hpurmann**
Instead of copying snippets and creating files locally, I want to only clone a provided repository when looking into an issue.
This advice will hopefully be followed by some people and thus simplify reproducing issues.

@torifat: Can we work on a small base repository with a `Dockerfile` and a `package.json` so that people could simply fork it? I saw your comment in https://github.com/yarnpkg/yarn/issues/1903 Maybe we can chat on Discord?

### CODE REVIEW

**Comment by torifat** [comment]
Yes, I have one. I can publish it into docker.

> Instead of copying snippets and creating files locally

But, how it will solve this? You still need to run most of the commands.

I only use docker for testing `ubuntu` related stuff.

**Comment by hpurmann** [comment]
I imagine a workflow where the issue reporter only has to

1. Fork base repository
1. Edit `package.json` and add scripts necessary
1. Push to his fork

Then anyone trying to reproduce could

1. Clone the fork
1. Docker build & docker run
1. Execute command inside the container (maybe even a `yarn test`)

Btw: What is your chicken and egg problem?

**Comment by torifat** [comment]
>  What is your chicken and egg problem?

I was working on a `Dockerfile` for development environment. So, when you start the container it will run `gulp watch` but the problem is you need `yarn`/`npm` to install `gulp` 😄

**Comment by hpurmann** [comment]
Ah ok. But this is not specific to a dev environment inside of Docker, right? If I do this on the host, I also have to execute `yarn install`/`npm install` before starting to work on `yarn`.

I don't think this is a big problem. The `yarn` binary you are using should be stable though.

When developing a compiler, it's pretty common to write the compiler _in the language it compiles_ (e.g. CoffeeScript, Rust, Scala). For more information, [see this thread on stackoverflow](http://stackoverflow.com/questions/193560/writing-a-compiler-in-its-own-language).

**Comment by hpurmann** [comment]
Any comments on the actual PR? @torifat ?

**Comment by torifat** [comment]
This would be too much to ask IMO. Please don't even want to follow issue template.

Instead I was thinking about something like `yarn report`, which will send `yarn-error.log`, `os`, `node`, & `yarn` version, & other useful `env` info.

**Comment by hpurmann** [comment]
Oh yeah, `yarn report` sounds like a nice idea. So it would output this to `stdout`, ready to be copied?

**Comment by torifat** [comment]
I was thinking about posting it to a `gist` and then give user a link.

**Comment by hpurmann** [comment]
Ok but then you require a GitHub token, right?

**Comment by bestander** [comment]
Great ideas expressed here, people!
I love the idea of automating the sharing experience of package.json or repro steps.

**Pull request merged**
