### PR TITLE
Create .npmignore on init, ignoring yarn.lock

### PR DESCRIPTION
**Pull request by gabro**
**Summary**
Essentially this: https://twitter.com/gabro27/status/786825544998481920

`yarn.lock` is a big file and shouldn't be included when publishing to npm.
This PR adds the creation of a `.npmignore` file that ignores `yarn.lock` when running `yarn init`.

The intent is to mitigate the risk of accidentally publishing that file.

**Test plan**
I added a unit test for this.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Personally, I'd prefer if it's just ignored by default. I see no reason to include it as it's ignored by installing packages anyway.

**Comment by kittens** [comment]
If you use `yarn publish` we already ignore `yarn.lock`. I'm not sure it makes sense to have this sort of npm compat.

**Comment by gabro** [comment]
Fair point @kittens. My feeling is that people may use `yarn install` because it's so _damn fast_™ but then still use `npm publish` for publishing (maybe because they've build some tooling around it.

That being said, I understand it may be an edge-case scenario, so - ultimately - your call :)

**Comment by kentcdodds** [comment]
> If you use yarn publish we already ignore yarn.lock. I'm not sure it makes sense to have this sort of npm compat

I was unaware this was the behavior. That's exactly what I wanted. Thanks!

**Comment by bestander** [comment]
I agree with @kittens.
@gabro, thanks for the PR, it makes sense but we need to manage complexity to keep maintainability. 
So at this point we can just recommend people switch to `yarn publish` rather than smooth all npm-cli compat issues on yarn side..
Feel free to reopen.

**Comment by gabro** [comment]
Sure @bestander, I appreciate the reasons.
Thanks for the reply and keep up with the great work 👍

**Pull request closed without merging**
