### PR TITLE
Update fixture certificates to prevent false negatives during testing

### LINKED ISSUE #7436: Run `yarn test` would be failed with error: SSL_CTX_use_certificate:ca md too weak
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
```
 FAIL  __tests__/util/request-manager.js
  ✕ RequestManager.request with cafile (104ms)
  ✕ RequestManager.request with ca (string) (3ms)
  ✕ RequestManager.request with ca (array) (2ms)
  ✕ RequestManager.request with mutual TLS (2ms)

  ● RequestManager.request with cafile

    error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak

      20 |     cert: await fs.readFile(path.join(__dirname, '..', 'fixtures', 'certificates', 'server-cert.pem')),
      21 |   };
    > 22 |   const server = https.createServer(options, (req, res) => {
      23 |     res.end('ok');
      24 |   });
      25 |   try {

      at Object.<anonymous> (__tests__/util/request-manager.js:22:24)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13

Test Suites: 1 failed, 1 total
Tests:       4 failed, 11 passed, 15 total
Snapshots:   0 total
Time:        2.138s
Ran all test suites matching /__tests__\/util\/request-manager.js/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
- use Debian 10.0(buster), which [release](https://lists.debian.org/debian-announce/2019/msg00003.html) on 2019/07/06, or [sid](https://www.debian.org/releases/sid/) version.
- execute jest unit test, like follow command `yarn test-only __tests__/util/request-manager.js`

**What is the expected behavior?**
It will pass all test case.

**Please mention your node.js, yarn and operating system version.**
```
$ node -v
v12.6.0
$ yarn -v
1.18.0-0
$ uname -a
Linux 001713996ca0 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux
$ openssl version
OpenSSL 1.1.1c  28 May 2019
```

### PR DESCRIPTION
**Pull request by eilgin**
**Summary**

Fixes #7436 and should also fix the CI tests!

**Test plan**

```bash
yarn test-only __tests__/util/request-manager.js
```

It should output:
```
 PASS  __tests__/util/request-manager.js
...
```

### CODE REVIEW

**Comment by rockwyc992** [comment]
Great, but why not still use 4096 bits key size?

**Comment by eilgin** [comment]
> Great, but why not still use 4096 bits key size?

My bad. I've used the default key size value (e.g. 2048) instead of the previous size. I've fixed that!

**Comment by rockwyc992** [comment]
LGTM, have tested with debian 10.0 with following config.
```
# /etc/ssl/openssl.cnf
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2
```

**Comment by arcanis** [comment]
That's awesome, thanks!

**Pull request merged**
