### PR TITLE
fix(run): change run command to prioritize cwd/node_modules/.bin

### PR DESCRIPTION
**Pull request by priceld**
**Summary**
This change builds off of [#7151](https://github.com/yarnpkg/yarn/pull/7151) and fixes [#7748](https://github.com/yarnpkg/yarn/issues/7748).

The issue is that when a binary is hoisted and also installed in a workspace package, `yarn bin` and `yarn run` (from the workspace package) fail to use the correct binary (they use the hoisted binary instead of the locally installed binary).

This PR just changes the order in which the array of paths is built so that the CWD bin path has a higher precedence than the hoisted bin path.

**Test plan**
Added two new tests that verify the correct binary is executed when running `yarn run`. One test has the same binary installed in a workspace package and hoisted to the root. The other test just has a binary hoisted to the root. Both tests try to run their binaries from a workspace package and verify that the right binary was used.

### CODE REVIEW

**Comment by priceld** [comment]
@rally25rs @arcanis @BYK - just wanted to loop in some of the others that were on [#7151](https://github.com/yarnpkg/yarn/pull/7151)

**Comment by jasonmobley** [comment]
@BYK any chance you could provide review? It's a follow-up to #7151 which you reviewed. Thanks!

**Comment by jdmarshall** [comment]
What's needed to get this PR landed?

**Comment by jasonmobley** [comment]
@jdmarshall it needs conflicts resolved, but it has sat for months waiting for someone to review. Seems the maintainers have abandoned Yarn 1.x in favor of Berry.

**Comment by priceld** [comment]
Yarn 1 is no longer maintained. Closing.

**Pull request closed without merging**
