### PR TITLE
Remove unnecessary deps

### PR DESCRIPTION
**Pull request by chicoxyzzy**
React presets and plugins for Babel and ESLint are unnecessary cause React is not used in the project

### CODE REVIEW

**Comment by hzoo** [comment]
This was probably done for flow? We'll need to include the strip types plugin instead?

**Comment by hzoo** [comment]
I just tried to `git clone`, `yarn`, and `npm t` and got an error with `ESLint couldn't find the plugin "eslint-plugin-react"`

There's also a warning for this when running `yarn`

```
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "eslint-plugin-react@^5.2.2".
```

[Yarn's eslintConfig](https://github.com/yarnpkg/yarn/blob/master/package.json#L98) extends [eslint-config-fb-strict](https://github.com/facebook/jest/blob/master/packages/eslint-config-fb-strict/package.json#L13) which uses [eslint-config-fbjs](https://github.com/facebook/fbjs/blob/master/packages/eslint-config-fbjs/package.json#L24) which uses eslint-plugin-react as a peerDependency

**Comment by chicoxyzzy** [comment]
```
➜  yarn git:(master) ✗ npm t

> yarnpkg@0.15.1 test /Users/Chico/Projects/yarn
> npm run lint && npm run test-only


> yarnpkg@0.15.1 lint /Users/Chico/Projects/yarn
> eslint . && flow check

Found 0 errors

> yarnpkg@0.15.1 test-only /Users/Chico/Projects/yarn
> jest --coverage --verbose

 PASS  __tests__/commands/install.js (55.087s)
  ✓ integrity hash respects flat and production flags (3616ms)
  ✓ flat arg is inherited from root manifest (601ms)
  ✓ doesn't write new lockfile if existing one satisfied (8055ms)
  ✓ writes new lockfile if existing one isn't satisfied (519ms)
  ✓ install transitive optional dependency from lockfile (22458ms)
  ✓ root install from shrinkwrap
  ✓ root install with optional deps
  ✓ install file: protocol
  ✓ install renamed packages
  ✓ install from offline mirror
  ✓ install from git cache
  ✓ install should dedupe dependencies avoiding conflicts 0
  ✓ install should dedupe dependencies avoiding conflicts 1
  ✓ install should dedupe dependencies avoiding conflicts 2 (1ms)
  ✓ install should dedupe dependencies avoiding conflicts 3
  ✓ install should dedupe dependencies avoiding conflicts 4
  ✓ install should dedupe dependencies avoiding conflicts 5
  ✓ install should dedupe dependencies avoiding conflicts 6 (jest/jest-runtime case)
  ✓ install should dedupe dependencies avoiding conflicts 7
  ✓ install should dedupe dependencies avoiding conflicts 8 (16756ms)
  ✓ install should dedupe dependencies avoiding conflicts 9 (398ms)
  ✓ install have a clean node_modules after lockfile update (branch switch scenario)
  ✓ install have a clean node_modules after lockfile update (branch switch scenario 2)
  ✓ uninstall should remove dependency from package.json, yarn.lock and node_modules
  ✓ uninstall should remove subdependencies
  ✓ check should verify that top level dependencies are installed correctly
  ✓ install should run install scripts in the order of dependencies
  ✓ run install scripts in the order when one dependency does not have install script
  ✓ install should circumvent circular dependencies
  ✓ install should resolve circular dependencies 2
  ✓ install should add missing deps to yarn and mirror (PR import scenario)
  ○ install should update a dependency to yarn and mirror (PR import scenario 2)
  ✓ install cache symlinks properly

 PASS  __tests__/commands/add.js (55.999s)
  ✓ install with arg that has install scripts (28781ms)
  ✓ install with arg (2ms)
  ✓ install with arg that has binaries (1ms)
  ✓ add should ignore cache
  ✓ add should not make package.json strict
  ✓ add --save-exact should not make all package.json strict
  ✓ add with new dependency should be deterministic 3 (26878ms)
  ✓ install --initMirror should add init mirror deps from package.json
  ✓ add with new dependency should be deterministic
  ○ add with new dependency should be deterministic 2 (1ms)
  ✓ add with offline mirror
  ✓ install with --save and without offline mirror
  ✓ upgrade scenario
  ✓ upgrade scenario 2 (with sub dependencies)
  ✓ downgrade scenario
  ✓ modules resolved multiple times should save to mirror correctly
  ✓ add should put a git dependency to mirror

 PASS  __tests__/normalize-manifest.js
  ✓ author object normalize (63ms)
  ✓ author string (41ms)
  ✓ authors file to contributors (14ms)
  ✓ bin string (12ms)
  ✓ binding.gyp scripts.install (10ms)
  ✓ bugs string (9ms)
  ✓ bundledDependencies alias (11ms)
  ✓ clean version (12ms)
  ✓ contributors array expand (10ms)
  ✓ dedupe dependencies (10ms)
  ✓ dedupe dependencies root (11ms)
  ✓ dedupe optionalDependencies (13ms)
  ✓ dedupe optionalDependencies root (10ms)
  ✓ engines array (12ms)
  ✓ explode directories.bin (24ms)
  ✓ explode directories.man (11ms)
  ✓ extract description (13ms)
  ✓ homepage string (11ms)
  ✓ hosted git repository url (23ms)
  ✓ keywords string (11ms)
  ✓ maintainers array expand (9ms)
  ✓ man string (8ms)
  ✓ name (11ms)
  ✓ readme (12ms)
  ✓ repository string (9ms)
  ✓ server scripts.start (11ms)
  ✓ throw name blacklist (8ms)
  ✓ throw name illegal character (11ms)
  ✓ throw name non-string (11ms)
  ✓ throw name start dot (9ms)
  ✓ throw name url encode required (8ms)
  ✓ valid license (12ms)
  ✓ version (12ms)
  ✓ warn builtin module collision (11ms)
  ✓ warn invalid license (21ms)
  ✓ warn typo (9ms)
  ✓ util.stringifyPerson (1ms)
  ✓ util.parsePerson (1ms)
  ✓ util.extractDescription (1ms)

 PASS  __tests__/lockfile.js
  ✓ parse/stringify 1 (7ms)
  ✓ parse/stringify 2 (1ms)
  ✓ parse/stringify 3 (1ms)
  ✓ parse/stringify 4 (1ms)
  ✓ parse (6ms)
  ✓ stringify (1ms)
  ✓ Lockfile.fromDirectory
  ✓ Lockfile.getLocked (7ms)
  ✓ Lockfile.getLocked pointer
  ✓ Lockfile.getLocked no cache (1ms)
  ✓ Lockfile.getLocked defaults (2ms)
  ✓ Lockfile.getLocked unknown
  ✓ Lockfile.getLockfile (4ms)
  ✓ Lockfile.getLockfile (sorting) (1ms)

 PASS  __tests__/reporters/console.js
  ✓ ConsoleReporter.step (17ms)
  ✓ ConsoleReporter.header (2ms)
  ✓ ConsoleReporter.footer (3ms)
  ✓ ConsoleReporter.log (1ms)
  ✓ ConsoleReporter.success (2ms)
  ✓ ConsoleReporter.error (2ms)
  ✓ ConsoleReporter.info (1ms)
  ✓ ConsoleReporter.command (1ms)
  ✓ ConsoleReporter.warn (1ms)
  ✓ ConsoleReporter.activity (98ms)
  ✓ ConsoleReporter.select (20ms)
  ✓ ConsoleReporter.progress (120ms)
  ✓ ProgressBar (4ms)
  ✓ Spinner (2ms)

 PASS  __tests__/reporters/console-reporter.js
  ✓ ConsoleReporter.step (3ms)
  ✓ ConsoleReporter.header (1ms)
  ✓ ConsoleReporter.footer (2ms)
  ✓ ConsoleReporter.log
  ✓ ConsoleReporter.success (1ms)
  ✓ ConsoleReporter.error
  ✓ ConsoleReporter.info
  ✓ ConsoleReporter.command (1ms)
  ✓ ConsoleReporter.warn (1ms)
  ✓ ConsoleReporter.activity (1ms)
  ✓ ConsoleReporter.select (3ms)
  ✓ ConsoleReporter.progress (3ms)
  ✓ ProgressBar (1ms)
  ✓ Spinner (1ms)

 PASS  __tests__/fetchers.js
  ✓ BaseFetcher.fetch (91ms)
  ✓ CopyFetcher.fetch (50ms)
  ✓ GitFetcher.fetch (3231ms)
  ✓ TarballFetcher.fetch (177ms)
  ✓ TarballFetcher.fetch throws (57ms)
  ✓ TarballFetcher.fetch supports local ungzipped tarball (36ms)

 PASS  __tests__/reporters/base-reporter.js
  ✓ BaseReporter.getTotalTime (5ms)
  ✓ BaseReporter.step
  ✓ BaseReporter.error
  ✓ BaseReporter.warn (1ms)
  ✓ BaseReporter.info
  ✓ BaseReporter.success
  ✓ BaseReporter.log
  ✓ BaseReporter.info
  ✓ BaseReporter.command
  ✓ BaseReporter.header
  ✓ BaseReporter.footer
  ✓ BaseReporter.activity
  ✓ BaseReporter.question (5ms)
  ✓ BaseReporter.select (2ms)
  ✓ BaseReporter.progress

 FAIL  __tests__/package-resolver.js (79.909s)
  ● resolve https://github.com/npm-ml/ocaml.git#npm-4.02.3

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at tryOnTimeout (timers.js:232:11)
      at Timer.listOnTimeout (timers.js:202:5)

  ✓ resolve github:PolymerElements/paper-elements (19802ms)
  ✓ resolve https://github.com/PolymerElements/font-roboto.git (2ms)
  ✓ resolve https://github.com/npm-ml/re (1ms)
  ✓ resolve https://bitbucket.org/hgarcia/node-bitbucket-api.git
  ✓ resolve https://github.com/PolymerElements/font-roboto/archive/2fd5c7bd715a24fb5b250298a140a3ba1b71fe46.tar.gz
  ✕ resolve https://github.com/npm-ml/ocaml.git#npm-4.02.3 (60012ms)
  ✓ resolve gitlab:leanlabsio/kanban
  ✓ resolve gist:d59975ac23e26ad4e25b
  ✓ resolve bitbucket:hgarcia/node-bitbucket-api
  ✓ resolve scrollin
  ✓ resolve gulp
  ✓ resolve react-native
  ✓ resolve ember-cli (1ms)
  ✓ resolve npm:gulp
  ✓ resolve @polymer/iron-icon (1ms)

 PASS  __tests__/reporters/json-reporter.js
  ✓ JSONReporter.step (6ms)
  ✓ JSONReporter.footer (1ms)
  ✓ JSONReporter.log (1ms)
  ✓ JSONReporter.command (2ms)
  ✓ JSONReporter.success (1ms)
  ✓ JSONReporter.error (1ms)
  ✓ JSONReporter.warn (2ms)
  ✓ JSONReporter.info (2ms)
  ✓ JSONReporter.activity (13ms)
  ✓ JSONReporter.progress (4ms)

 PASS  __tests__/util/promise.js
  ✓ promisify (5ms)
  ✓ promisifyObject (1ms)
  ✓ queue (1ms)

 PASS  __tests__/util/filter.js
  ✓ ignoreLinesToRegex (134ms)

 PASS  __tests__/reporters/event-reporter.js
  ✓ EventReporter.finished (3ms)
  ✓ EventReporter.step (1ms)
  ✓ EventReporter.log (1ms)
  ✓ EventReporter.success
  ✓ EventReporter.error (2ms)
  ✓ EventReporter.info (1ms)
  ✓ EventReporter.command (1ms)
  ✓ EventReporter.warn (1ms)

 PASS  __tests__/reporters/buffer-reporter.js
  ✓ BufferReporter.finished (3ms)
  ✓ BufferReporter.step (1ms)
  ✓ BufferReporter.log (1ms)
  ✓ BufferReporter.success (1ms)
  ✓ BufferReporter.error (1ms)
  ✓ BufferReporter.info (1ms)
  ✓ BufferReporter.command (1ms)
  ✓ BufferReporter.warn (1ms)

 PASS  __tests__/package-compatibility.js
  ✓ node semver semantics (24ms)

 PASS  __tests__/util/stream.js
  ✓ ConcatStream (12ms)

 PASS  __tests__/util/blocking-queue.js
  ✓ max concurrency (5ms)

 PASS  __tests__/util/git.js
  ✓ cleanUrl (15ms)

 PASS  __tests__/constants.js
  ✓ getPathKey (3ms)

---------------------------------|----------|----------|----------|----------|----------------|
File                             |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------------------|----------|----------|----------|----------|----------------|
All files                        |    76.16 |    64.26 |    83.24 |    80.91 |                |
 src                             |    84.09 |     68.9 |    90.09 |    87.22 |                |
  config.js                      |    87.72 |    71.67 |    93.33 |     93.2 |... 259,330,339 |
  constants.js                   |    97.06 |     62.5 |      100 |      100 |                |
  errors.js                      |      100 |      100 |      100 |      100 |                |
  package-compatibility.js       |    63.53 |    53.03 |    64.29 |    71.67 |... 162,165,171 |
  package-constraint-resolver.js |      100 |      100 |      100 |      100 |                |
  package-fetcher.js             |    75.86 |    59.09 |      100 |    84.09 |... 60,68,70,72 |
  package-hoister.js             |    97.65 |    90.32 |      100 |    97.55 | 68,228,365,366 |
  package-install-scripts.js     |    89.54 |    72.83 |      100 |    93.53 |... 145,149,168 |
  package-linker.js              |    87.14 |    64.58 |      100 |    90.43 |... 219,247,250 |
  package-reference.js           |    85.51 |    76.92 |    66.67 |    87.88 |... 104,106,118 |
  package-request.js             |    90.32 |       70 |     93.1 |    95.45 |... 211,232,296 |
  package-resolver.js            |    62.91 |    62.71 |    74.19 |    62.67 |... 312,333,338 |
 src/cli/commands                |    71.03 |    58.91 |    78.81 |    76.95 |                |
  _execute-lifecycle-script.js   |    68.42 |    58.33 |       60 |     62.5 |       17,18,19 |
  add.js                         |    70.59 |    59.68 |    77.27 |    72.73 |... 177,178,195 |
  check.js                       |    77.57 |    63.64 |    93.33 |    80.72 |... 167,171,180 |
  install.js                     |    62.38 |    52.36 |    75.95 |    56.25 |... 765,766,767 |
  ls.js                          |    92.42 |       80 |    77.78 |    91.11 |    91,92,94,95 |
  remove.js                      |    83.33 |    69.57 |    93.75 |    94.12 |          25,64 |
 src/fetchers                    |     76.4 |    67.65 |    93.55 |    89.47 |                |
  base-fetcher.js                |    74.07 |    63.64 |    90.91 |      100 |                |
  copy-fetcher.js                |    53.33 |    66.67 |      100 |      100 |                |
  git-fetcher.js                 |    77.78 |    66.67 |     87.5 |    88.37 | 32,53,59,60,63 |
  index.js                       |      100 |    83.33 |      100 |      100 |                |
  tarball-fetcher.js             |    79.49 |    68.42 |    95.65 |    86.36 |... 120,124,126 |
 src/lockfile                    |    86.15 |    82.09 |    85.37 |    98.33 |                |
  parse.js                       |    84.91 |    76.09 |    71.43 |      100 |                |
  stringify.js                   |    94.87 |    89.36 |      100 |      100 |                |
  wrapper.js                     |    83.87 |    85.48 |       90 |     97.5 |            150 |
 src/registries                  |    67.53 |    58.06 |    73.68 |    78.45 |                |
  base-registry.js               |    82.76 |       90 |    61.54 |    82.14 | 60,68,72,76,80 |
  bower-registry.js              |     61.9 |    59.09 |      100 |    90.91 |             29 |
  index.js                       |      100 |       90 |      100 |      100 |                |
  npm-registry.js                |    71.43 |    58.33 |    83.33 |       78 |... ,73,116,117 |
  yarn-registry.js               |    47.22 |    38.24 |    53.33 |    65.22 |... 78,79,83,91 |
 src/reporters                   |    62.86 |    55.56 |    68.48 |     68.1 |                |
  base-reporter.js               |    51.67 |    42.55 |    72.09 |    58.33 |... 193,194,200 |
  buffer-reporter.js             |      100 |    83.33 |      100 |      100 |                |
  event-reporter.js              |      100 |    83.33 |      100 |      100 |                |
  format.js                      |    66.67 |      100 |        0 |    66.67 |              4 |
  index.js                       |     62.5 |       40 |       40 |      100 |                |
  json-reporter.js               |    66.67 |    91.67 |    65.52 |    65.96 |... 86,89,95,98 |
 src/reporters/console           |    64.98 |    58.62 |    73.97 |     66.2 |                |
  console-reporter.js            |    56.97 |    56.16 |    69.64 |     57.5 |... 354,355,356 |
  progress-bar.js                |      100 |       75 |      100 |      100 |                |
  spinner-progress.js            |    91.67 |    83.33 |       75 |    95.65 |             60 |
  util.js                        |    56.52 |       50 |      100 |    55.56 |    35,36,37,38 |
 src/reporters/lang              |      100 |    83.33 |      100 |      100 |                |
  en.js                          |      100 |      100 |      100 |      100 |                |
  index.js                       |      100 |    83.33 |      100 |      100 |                |
 src/resolvers                   |     96.3 |    88.89 |    94.12 |    94.44 |                |
  base-resolver.js               |    91.67 |      100 |    66.67 |    91.67 |             40 |
  index.js                       |      100 |    88.89 |      100 |      100 |                |
 src/resolvers/exotics           |    71.63 |    59.45 |    88.24 |    79.36 |                |
  bitbucket-resolver.js          |      100 |    83.33 |      100 |      100 |                |
  exotic-resolver.js             |    83.33 |       75 |      100 |    83.33 |             13 |
  file-resolver.js               |    71.43 |    61.54 |       90 |    94.44 |             29 |
  gist-resolver.js               |       60 |     62.5 |    88.89 |    90.91 |             22 |
  git-resolver.js                |    65.28 |    51.52 |    83.33 |    73.81 |... 130,131,135 |
  github-resolver.js             |      100 |       90 |      100 |      100 |                |
  gitlab-resolver.js             |      100 |    83.33 |      100 |      100 |                |
  hosted-git-resolver.js         |    66.25 |    41.07 |       76 |    64.47 |... 188,189,193 |
  registry-resolver.js           |       90 |    66.67 |       80 |       90 |             17 |
  tarball-resolver.js            |    76.74 |       75 |      100 |    90.63 |       29,40,50 |
 src/resolvers/registries        |    48.94 |    47.92 |    74.19 |    52.44 |                |
  bower-resolver.js              |    88.89 |    71.43 |     87.5 |     87.5 |             25 |
  npm-resolver.js                |    38.96 |    37.14 |    61.11 |    42.42 |... 124,132,145 |
  registry-resolver.js           |      100 |    83.33 |      100 |      100 |                |
  yarn-resolver.js               |      100 |    83.33 |      100 |      100 |                |
 src/util                        |    74.47 |    58.46 |    83.33 |     78.7 |                |
  blocking-queue.js              |    92.98 |    78.13 |      100 |    92.98 |    52,53,84,85 |
  child.js                       |    70.59 |    56.52 |    85.71 |    77.78 |... 50,61,79,87 |
  crypto.js                      |    92.31 |        0 |       80 |    90.91 |             37 |
  execute-lifecycle-script.js    |    84.21 |    73.68 |      100 |    94.74 |          68,74 |
  filter.js                      |    30.91 |    31.43 |       60 |    61.11 |... 110,111,136 |
  fs.js                          |    86.15 |    62.96 |    94.74 |      100 |                |
  git.js                         |    66.92 |    51.38 |    76.47 |    68.64 |... 263,275,329 |
  map.js                         |      100 |      100 |      100 |      100 |                |
  misc.js                        |      100 |    83.33 |      100 |      100 |                |
  network.js                     |    92.86 |       75 |      100 |    90.91 |             25 |
  promise.js                     |    94.87 |      100 |    81.82 |      100 |                |
  request-manager.js             |    62.84 |    50.44 |       68 |    65.22 |... 369,370,371 |
  stream.js                      |    97.37 |      100 |     87.5 |      100 |                |
  version.js                     |      100 |      100 |      100 |      100 |                |
 src/util/normalize-manifest     |    92.25 |     83.7 |      100 |    98.46 |                |
  fix.js                         |    66.67 |       50 |      100 |      100 |                |
  index.js                       |      100 |       75 |      100 |      100 |                |
  infer-license.js               |      100 |    83.33 |      100 |      100 |                |
  licenses.js                    |      100 |      100 |      100 |      100 |                |
  typos.js                       |      100 |      100 |      100 |      100 |                |
  util.js                        |      100 |      100 |      100 |      100 |                |
  validate.js                    |    91.89 |       80 |      100 |       95 |            118 |
---------------------------------|----------|----------|----------|----------|----------------|
Test Suites: 1 failed, 1 skipped, 18 passed, 19 of 20 total
Tests:       1 failed, 4 skipped, 199 passed, 204 total
Snapshots:   57 passed, 57 total
Time:        200.928s
Ran all test suites.

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/Chico/.nvm/versions/node/v6.7.0/bin/node" "/Users/Chico/.nvm/versions/node/v6.7.0/bin/npm" "run" "test-only"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! yarnpkg@0.15.1 test-only: `jest --coverage --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yarnpkg@0.15.1 test-only script 'jest --coverage --verbose'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yarnpkg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest --coverage --verbose
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yarnpkg
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yarnpkg
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Chico/Projects/yarn/npm-debug.log
npm ERR! Test failed.  See above for more details.
➜  yarn git:(master) ✗
```

I see here only one test failing and not because of missing dependency.

I think `eslint-config-fbjs` should have `eslint-plugin-react` as [optional dependancy](https://docs.npmjs.com/files/package.json#optionaldependencies) but I agree that this should be solved somehow.

**Comment by Daniel15** [comment]
Sounds like this caused some issues, so I submitted a revert diff: #703

**Comment by hzoo** [comment]
@Daniel15 yeah I made https://github.com/yarnpkg/yarn/pull/701 - it's a peerDep of a eslint config

**Comment by ljharb** [comment]
Optional deps would not be appropriate. They are still installed, it's just that failure to install won't kill the whole process.

**Comment by chicoxyzzy** [comment]
Maybe I have a different version of npm than @hzoo but I didn't get any errors. There was only npm warning. Circle CI tests passed as well https://circleci.com/gh/yarnpkg/yarn/1049

**Pull request merged**
