### PR TITLE
Ignore unused patterns to avoid dev dependencies download when installing with --production flag (#3312)

### PR DESCRIPTION
**Pull request by pichouk**
**Summary**
As described on #3312, `yarn` do not consider the `--production` flag when installing packages (with `yarn install --production`) and try to download dev dependencies too. It can be really annoying since, sometimes, production environment does not have access to private packages used in development. 
I try to set a boolean to `true` which, I guess, will disable this behavior and only download real dependencies.

**Test plan**
I build my modified version of `yarn` and test some install to verify it have the correct behavior.

On an empty folder with the following `package.json` (notice the not existing package in `devDependencies`) :
```
{
  "name": "testproject",
  "version": "0.5.6",
  "license": "UNLICENSED",
  "description": "Fake project to test yarn install --production",
  "dependencies": {
    "lodash": "^4.17.4"
  },
  "devDependencies": {
    "notExistingProjeCt": "^1.17.65"
  }
}
```

Install with version `0.24.5` :
```
kyane@kyane-pc:/tmp/test-yarn$ yarn --version
0.24.5
kyane@kyane-pc:/tmp/test-yarn$ yarn install --production
yarn install v0.24.5
[1/4] Resolving packages...
error Couldn't find package "notExistingProjeCt" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Install with my modified version :
```
kyane@kyane-pc:/tmp/test-yarn$ ~/code/yarn/dist/bin/yarn --version
0.26.0-0
kyane@kyane-pc:/tmp/test-yarn$ ~/code/yarn/dist/bin/yarn install --production
yarn install v0.26.0-0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.42s.
```

Can see that `yarn` does not try to resolve dev dependencies anymore :)

### CODE REVIEW

**Comment by pichouk** [comment]
Ok tests failed, seems more complicated that I was thinking...

**Comment by bestander** [comment]
Yeah, it is more complex.
We still need to resolve all dev dependencies but we need to not fetch them in package-fetcher.

**Comment by bestander** [comment]
Thanks for giving it a try, @pichouk!
Much appreciated.

**Comment by pichouk** [comment]
@bestander I searched a little tonight and I cannot found have to solve this.
It seem that the `markIgnored` function in `src/cli/commands/install.js` *need* to resolve package to mark it as ignored. And the resolving step raise an error when the dependency is not accessible (eg. a private dev dependency). I don't know how to do it, I'll see later but maybe it is too difficult for a "Yarn newbie" :p

**Comment by pichouk** [comment]
Closing since I have not real solution for this issue.
I guess Yarn assume that all dependencies (even dev dependencies) should be resolved even when using `--production` flag. I think it is really annoying since you cannot install a project using only public dependencies on production if there is some private dev dependencies...

**Pull request closed without merging**
