### PR TITLE
Reroll #1816 into a new PR + fix for test failures

### PR DESCRIPTION
**Pull request by chrisirhc**
**Summary**

Intended to solve #573 . This is a re-application of the changes in #1816 but with a fix for the tests in 3c55f6ba63aa87a87f7429f5e8e081004fc8664b. All work is credited to @f-sign . Only attempting to re-run tests and clean up the PR so it doesn't have duplicate commits from master.

**Test plan**

Tests pass. Left it up to author of #1816 .

**Background**

This originated from investigating https://github.com/yarnpkg/yarn/pull/1816#issuecomment-270288503 .

### CODE REVIEW

**Comment by gaving** [comment]
Not sure if it's related to the tests or not, but I've the same issue as [this](https://github.com/yarnpkg/yarn/pull/1816#issuecomment-269774544) after running `npm install https://github.com/yarnpkg/yarn#pull/2384/head -g`

**Comment by bestander** [comment]
@gaving, that is a neat way to install yarn from a PR!

Does the issue with `../lib-legacy/constants` reproduce only when you install thisPR?
I doubt it is related to the PR.
It looks more like the .roadrunner cache got invalid and does not clear, try running `yarn cache clean`

**Comment by bestander** [comment]
Thanks @chrisirhc  and @f-sign, I merged without squashing

**Comment by gaving** [comment]
@bestander Ahh good point, tried with another PR and master even and got the same error.

Sorry for the noise, looking forward to a release!

**Comment by sudowork** [comment]
I'm still running into the same issue even after building from master or using the latest nightly build (`v0.19.0-20170106.1725`):

```shell
$ yarn install
yarn install v0.19.0-20170106.1725
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: clone ssh://git@github.com:githubuser/repo.git /Users/username/Library/Caches/Yarn/.tmp/bff4d24c292f2c5f1a876330de56ef81
Directory: /Users/username/project
Output:
Cloning into '/Users/username/Library/Caches/Yarn/.tmp/bff4d24c292f2c5f1a876330de56ef81'...
ssh: Could not resolve hostname github.com:githubuser: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

$ git clone git@github.com:githubuser/repo.git # Just a sanity check
Cloning into 'repo'...
remote: Counting objects: 35, done.
remote: Total 35 (delta 0), reused 0 (delta 0), pack-reused 35
Receiving objects: 100% (35/35), 9.79 KiB | 0 bytes/s, done.
Resolving deltas: 100% (10/10), done.
```

**Comment by gaving** [comment]
Replicating @sudowork's behaviour after a `npm install yarn@0.19.0`.

**Comment by gaving** [comment]
Actually after revisiting [this comment](https://github.com/yarnpkg/yarn/issues/513#issuecomment-254850558), things now appear to work for me (didn't before).

Trick is to change URL format:-

`git+ssh://git@host:org/repo.git`

  to

`git+ssh://git@host/org/repo.git`

Not sure if the semicolon version is supposed to work after this PR, but I'm just happy something is working now. 😄 

Full example:-

    root@7cf94c933636:/var/www/test# cat package.json
    {
      "dependencies": {
        "test": "git+ssh://git@git.mbp.local/test/client-node.git"
      }
    }
    root@7cf94c933636:/var/www/test# yarn install
    warning No license field
    yarn install v0.19.0
    info No lockfile found.
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    success Saved lockfile.
    Done in 22.94s.
    root@7cf94c933636:/var/www/test# git clone git+ssh://git@git.mbp.local/test/client-node.git test
    Cloning into 'test'...
    Please disconnect now if you are not authorised.
    remote: Counting objects: 37, done.
    remote: Compressing objects: 100% (34/34), done.
    remote: Total 37 (delta 15), reused 0 (delta 0)
    Receiving objects: 100% (37/37), 6.16 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (15/15), done.
    Checking connectivity... done.

**Comment by sudowork** [comment]
@gaving, Based on the tests, I believe that using the colon separator is supposed to be working. https://github.com/yarnpkg/yarn/pull/2384/commits/477c612dcaefde11c92ff188a87d34655c3e80f2#diff-00109fff57c65d5eba87e219e6d5a825R44

**Comment by thepian** [comment]
So how are you supposed to use yarn with SSH, it seems clear as mud and if possible more hacky than with npm?

**Pull request merged**
