### PR TITLE
Fix: workspace support in several commands

### LINKED ISSUE #4328: yarn outdated not working w/workspaces
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In a project work workspaces, `yarn outdated` claims everything is up to date. (The root project has no dependences). `yarn workspace api outdated` errors with the following:

```
yarn workspace v1.0.0
yarn outdated v1.0.0
error No lockfile in this directory. Run `yarn install` to generate one.
error Command failed.
Exit code: 1
Command: /usr/local/Cellar/node/8.4.0/bin/node
Arguments: /usr/local/Cellar/yarn/1.0.0_1/libexec/lib/cli.js outdated
Directory: /Volumes/git/project/packages/api
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I expect it to tell me the outdated modules.

**Please mention your node.js, yarn and operating system version.**

yarn 1.0.0

### LINKED ISSUE #4334: "yarn remove" inside workspace fails
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

Attempting to remove a package from inside a workspace fails with:

```
error No lockfile in this directory. Run `yarn install` to generate one
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```sh
$ cd packages/some-package
$ yarn remove some-dependency
yarn remove v1.0.1
error No lockfile in this directory. Run `yarn install` to generate one
```

**What is the expected behavior?**

The package should be removed and the root lockfile should be updated.

**Please mention your node.js, yarn and operating system version.**

Node 8.4.0
Yarn 1.0.1
Mac OS 10.12

Possibly related to #4328.

### LINKED ISSUE #4348: Adding root dependency removes workspace packages from lockfile
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

Adding a dev dependency to the root of a workspace adds the new package to the lockfile, but also removes lockfile entries for dependencies of the individual workspaces.

In my project, adding a single dependency to the root trimmed the lockfile length from ~8000 lines to ~4000. The workaround is to use `--no-lockfile` when adding, and then run `yarn install`; this will add just the new dependency to the lockfile, as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**

In a workspace project:

```sh
$ yarn add --dev left-pad # in workspace root
```

This will remove entries from the lockfile that aren't direct dependencies of the root (e.g., are dependencies of the workspaces).

**What is the expected behavior?**

Lockfile is updated with just an entry for the new dependency.

**Workaround**

```sh
$ yarn add --dev --no-lockfile left-pad
$ yarn install
```

This will update `package.json` with the new entry only, and then update the lockfile as part of `yarn install`, which produces the correct results.

**Please mention your node.js, yarn and operating system version.**
Node: 8.4.0
Yarn: 1.0.1
OS: Mac OS 10.12

### PR DESCRIPTION
**Pull request by jgoz**
**Summary**

Fixes #4334
Fixes #4328
Fixes #4348

(Follow-up to #4630, #4583).

This gets several commands working when used in a workspace-enabled solution:

- `outdated`:
  - when used in a workspace root or any child packages, it will show outdated packages across the entire workspace
  - added "Workspace" column to show where the outdated package is installed
- `remove`:
  - when used in a workspace root, removes given package from the root only
  - when used in a workspace child, removes given package from that child only
- `upgrade`:
  - when used in a workspace root, upgrades given package in root only
  - when used in a workspace child, upgrades given package in child only
- `upgrade-interactive`:
  - shows outdated packages across entire workspace, and can upgrade any/all
  - added "workspace" column to show where outdated package is installed

This is slightly different from how @arcanis described in #4630, specifically with `upgrade`. I thought it would be less confusing/frustrating for users, especially if child workspaces have conflicting versions of the same dependency. Rather than forcing them all to the same version, this allows for fine-grained control while offering a whole-workspace upgrade option with `upgrade-interactive`.

**Test plan**

- Added tests where appropriate
- Existing tests pass
- Screenshots of updated command output below:

`outdated` with "Workspace" column:
image

`upgrade-interactive` with "workspace" column:
image

### CODE REVIEW

**Comment by JohnFultonian** [comment]
Thanks for your work on this, we just started using yarn workspaces recently and this will make our lives a lot easier.

**Comment by arcanis** [comment]
> This is slightly different from how @arcanis described in #4630, specifically with upgrade. I thought it would be less confusing/frustrating for users, especially if child workspaces have conflicting versions of the same dependency.

Then how does it work if A and B both depend on C@~1.0.0, and you run `yarn upgrade C` from inside A? It will upgrade C in both A and B, right?

**Comment by jgoz** [comment]
> Then how does it work if A and B both depend on C@~1.0.0, and you run yarn upgrade C from inside A? It will upgrade C in both A and B, right?

No, it will only upgrade C in A, and the lockfile will now have two entries for C. If you run `yarn upgrade C` in B, then they will once again converge.

This is a choice that was initially dictated by the complexity of implementing it the way you described it (where it upgrades C in both A and B when you run the command from just one workspace). There were a couple of issues to deal with here:
- What if C is a `dependency` in A and a `devDependency` in B? We would need to change the way `upgrade` works to be more like `upgrade-interactive`, where it runs install multiple times to ensure that difference is preserved.
- How would a user indicate that they _only_ want to upgrade C in A, leaving the version as ~1.0.0 in B? We would need to add a CLI flag or something to toggle this behaviour.

Then I thought about `add` and `remove`. Those only operate on a single workspace child/root, so having `upgrade` work this way too is arguably less confusing and more consistent. That it avoids bigger changes, refactoring in `install`, and extra flags is a bonus. And for upgrading C in both A and B, we can use `upgrade-interactive`.

**Comment by arcanis** [comment]
i-ship-it-gif-16

**Comment by vvo** [comment]
awesome work, thanks

**Comment by ericclemmons** [comment]
I just tested #4469 with v1.2.0 and it works now! 👏

**Comment by milesj** [comment]
@jgoz Awesome work on this PR. Such a life saver and it's been working flawlessly!

**Pull request merged**
