### PR TITLE
Correctly resolve peerDependencies for concurrent installs

### PR DESCRIPTION
**Pull request by kamilogorek**
**Summary**

When installing multiple packages at the same time eg. `yarn add react react-dom`, `peerDependencies` were incorrectly resolved and triggered warnings.

Related: https://github.com/yarnpkg/yarn/issues/2132

**Test plan**

### Before:
```
λ: yarn add request request-promise-native
yarn add v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
warning "request-promise-native@1.0.3" has unmet peer dependency "request@^2.34".
[4/4] 📃  Building fresh packages...
success Saved 2 new dependencies.
├─ request-promise-native@1.0.3
└─ request@2.79.0
✨  Done in 6.05s.

λ: yarn add react react-dom
yarn add v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-dom@15.4.2" has unmet peer dependency "react@^15.4.2".
[4/4] 📃  Building fresh packages...
success Saved 2 new dependencies.
├─ react-dom@15.4.2
└─ react@15.4.2
✨  Done in 5.65s.
```

### After:
```
λ: yarn add request request-promise-native
yarn add v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved 2 new dependencies.
├─ request-promise-native@1.0.3
└─ request@2.79.0
✨  Done in 5.67s.

λ: yarn add react react-dom
yarn add v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved 2 new dependencies.
├─ react-dom@15.4.2
└─ react@15.4.2
✨  Done in 5.65s.
```

### CODE REVIEW

**Comment by bestander** [comment]
Cool, thanks a lot!
Can you add a case when warning is expected to the Test Plan?
Could you add a unit test for that?

**Comment by ev1stensberg** [comment]
Sweet, I'll close my PR :)

**Comment by kamilogorek** [comment]
@bestander updated PR with tests for all 3 cases

**Comment by bestander** [comment]
🥇

**Pull request merged**
