### PR TITLE
Add vendor informations to licences ls command

### PR DESCRIPTION
**Pull request by lochbrunner**
**Summary**

No. It only adds two columns to the output of a reporting feature.

Often when using OpenSource Software one has to make a finer report of the used dependencies. For example Vendor/Author name and homepage is a must.
The current feature provided by yarn is nice, but still not sufficient for commercial use.

**Test plan**

I ran
```bash
yarn licenses ls --json > licenses.json
```
Results in a large json output. A cut of them looks like

```json
{
    "type": "table",
    "data": {
        "head": [
            "Name",
            "Version",
            "License",
            "URL",
            "VendorUrl",
            "vendorName"
        ],
        "body": [
            [
                "ansi-regex",
                "2.1.1",
                "MIT",
                "https://github.com/chalk/ansi-regex.git",
                "sindresorhus.com",
                "Sindre Sorhus"
            ],
            [
                "aws-sign2",
                "0.6.0",
                "Apache-2.0",
                "https://github.com/mikeal/aws-sign",
                "http://www.futurealoof.com",
                "Mikeal Rogers"
            ],
```

### CODE REVIEW

**Comment by voxsim** [comment]
Hey @lochbrunner that's a wonderful idea :D Could you please write some tests that do the same stuff that you do manually? If you need some help I am here ;)

**Comment by lochbrunner** [comment]
Hi @voxsim, 
by now, there are no tests for the `licenses` command at all. I will read into the tests for the `list` command and try to write some for the `licenses` command. Or did I overlooked it?

**Comment by voxsim** [comment]
@lochbrunner you are right, that's why if for some reasons you find some difficulties I am here to help you. Can you help us? Do you have time? ;)

**Comment by lochbrunner** [comment]
@voxsim, thanks for your support.
The yarn project is quite interesting and I want to understand its design and toolchain more detailed! But unfortunately not today, but tomorrow.

**Comment by lochbrunner** [comment]
Hi @voxsim how do you get the table typed result of the `JSONReporter` ?
Using the CLI one gets it automatically. But when writing a test one gets the tree typed result.

My test runner looks as follow:

```JavaScript
const runLicenses = buildRun.bind(
  null,
  JSONReporter,
  fixturesLoc,
  async (args, flags, config, reporter, lockfile, getStdout): Promise<string> => {
    await licenses(config, reporter, flags, args);
    return getStdout();
  },
);

test('lists all licenses of the dependencies with the --json argument', async(): Promise<void>  => {
  await runLicenses(['ls'], {}, '', (config, reporter, stdout) => {
    expect(stdout).toContain(JSON.stringify(expectedTable));
  });
});

```

**Comment by voxsim** [comment]
@lochbrunner it's perfect! awesome! :D Could you please call `expected-table.json` instead of`table.json`?

**Comment by lochbrunner** [comment]
@voxsim Done!

**Comment by voxsim** [comment]
Let's wait for the result and merge it if everything is ok :)

**Comment by lochbrunner** [comment]
What to do with the failed test run? It's a timeout issue.

**Pull request merged**
