### PR TITLE
feat(audit): select which dependency groups to audit

### LINKED ISSUE #6632: Add a flag to ignore devDependencies when running yarn audit
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

When running `yarn audit` dev dependencies are included in the check.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Add a flag to ignore dev dependencies when running the audit. This has also been reported on https://github.com/npm/npm/issues/20564.

Perhaps the `--production` flag could be used for this?

**Please mention your node.js, yarn and operating system version.**

Mac:  10.14 (18A391)
Node: v8.11.3
Yarn: 1.12.1

### PR DESCRIPTION
**Pull request by tommilligan**
**Summary**

Closes #6632.

Currently `yarn audit` shows vulnerabilities for production, development and optional dependencies. It would be useful to only audit production dependencies, or select which groups of dependencies to audit.

**Test plan**

##### master
```
$ yarn audit --prod
...
9 vulnerabilities found - Packages audited: 31177
Severity: 9 Low
Done in 2.24s.
```

##### this PR
```
$ yarn audit --groups dependencies
...
0 vulnerabilities found - Packages audited: 442
Done in 2.08s.
```

---

I look forward to hearing some feedback!

### CODE REVIEW

**Comment by Jalle19** [comment]
Looks like a pragmatic solution to me (commenting here mostly to get notified if this moves forward)

**Comment by syrnick** [comment]
Very helpful!

**Comment by Jalle19** [comment]
Any updates on this?

**Comment by charrondev** [comment]
Are any of the maintainers going to chime in here? Without this it is difficult to run audits in CI. My team is going to stop the world because of a low severity DoS in our test runner for example. We do want to stop the world and fix a higher severity issue in a package shipped to production however.

**Comment by iflp** [comment]
@arcanis - please take a look at this, thanks!

**Comment by arcanis** [comment]
Ping @rally25rs ?

**Comment by rally25rs** [comment]
@tommilligan it looks like some of the audit unit tests now fail due to another change to audit that adds   whether or not it is a dev dep. Would you mind resolving the failing tests? (or I'll see if I can push a commit to fix it...)

**Comment by OZZlE** [comment]
Seems like a great idea but doesn't seem to work, it's complaining about devDepencencies anyway

**Pull request merged**
