### PR TITLE
chore: Better error handling and tests in TarballFetcher

### PR DESCRIPTION
**Pull request by sth**
**Summary**

Currently `TarballFetcher.fetch()` doesn't notice when a truncated tar is extracted, the extracted directory will simply be incomplete. This pull request updates tar-stream to the newest version to detect these errors and show a useful message to the user.

**Test plan**

Tests are added that show that the current code didn't work correctly, and that the updated code does.

### CODE REVIEW

**Comment by sth** [comment]
The buildsize increased due to the updated dependencies of `tar-stream`.

**Comment by BYK** [comment]
Looks really nice, thanks! Pinged @rally25rs and @imsnif for an more detailed review but overall it looks very clean and complete with tests.

**Comment by imsnif** [comment]
Hey @sth - is this ready for another review now?

**Comment by sth** [comment]
@imsnif @byk Yes, I think it's ready.

**Comment by sth** [comment]
@BYK The requested changes have been addressed, could you have another look?

**Comment by BYK** [comment]
@sth - oh sorry, I didn't realize I was blocking.

Looks good to me overall but seems like we ignore errors from the gzip decompression. Am I right?

**Comment by sth** [comment]
@BYK: Yes, those errors are currently ignored. I have plans to fix that next, but decided to take it one step at a time (there are also quite a few other places that could use test cases for errors and might not work correctly when something goes wrong).

**Comment by sth** [comment]
To elaborate a bit of my last comment: Decompression errors are ignored, but that's not something new in this pull request. The old code also ignores them. The error handler was in a different place but it didn't catch decompression errors there either, since since error events don't bubble through pipes.

**Pull request merged**
