### PR TITLE
Disables a tarball fetching test on windows

### PR DESCRIPTION
**Pull request by arcanis**
**Summary**

AppVeyor is constantly timeouting on the tarball fetching test.

**Test plan**

n/a

### CODE REVIEW

**Comment by Daniel15** [comment]
Why does the test load data from the internet, rather than using mocked data?

**Comment by arcanis** [comment]
I think the problem here is that those integration tests are executed by running an actual yarn process. They don't run in Jest, so they can't be mocked. I'm not entirely sure though, maybe @bestander remembers?

**Comment by Gudahtt** [comment]
I was hoping to look into why these are failing soon. It definitely makes sense to skip them for now.

The test suite is extremely slow and flaky on Windows right now, these two being the worst. I was thinking it might be related to this issue: https://github.com/sindresorhus/execa/issues/142

**Comment by rockwyc992** [comment]
Are there any issue, like #4073, to track this problem?

**Pull request merged**
