### PR TITLE
Remove devDependencies resolution in production mode

### LINKED ISSUE #761: `yarn install --production` doesn't install correct dependencies
When running `yarn install --production` it does not install the required dependencies of `forever`.  This seem to be related to having`nodemon` in `devDependencies`. 

Error response:

``` console
> forever app.js
module.js:457
    throw err;
    ^
Error: Cannot find module 'minimatch'
```

I've created a test application here:
https://github.com/donovan-graham/yarn-example-app

``` sh
#  Steps to reproduce error
git clone https://github.com/donovan-graham/yarn-example-app.git
cd yarn-example-app
yarn install --production
npm start

#  temporary step to bypass error
rm -rf node_modules
yarn remove nodemon
yarn install --production
npm start
```

### PR DESCRIPTION
**Pull request by torifat**
When `dependencies` & `devDependencies` have common dependency, it fails in `production` mode.

**TODO**
- [x] Add test

Fixes #761, #1014

### CODE REVIEW

**Comment by torifat** [comment]
761 is a different issue. `entries-test` contains `node_modules` folder. 

https://registry.yarnpkg.com/entries-test/-/entries-test-1.0.1.tgz#1bf192e414ceadd0cf4b77b3969df32de2985d50

**Comment by torifat** [comment]
Nested shared dependency doesn't work when `yarn --production`. Only `dep-a` & `dep-c` get installed.

screenshot 2016-11-27 19 51 51

**Comment by kittens** [comment]
This isn't a correct fix, we need to consider dev dependencies when we're performing package hoisting so the same hoisting structure is retained in dev and prod. The `visibility` flag is what toggles this.

**Comment by torifat** [comment]
@kittens ok, got it. I thought it wouldn't matter. If you want to work on it then you can use my test case.

**Comment by torifat** [comment]
I can give it a try too. But, might need some time 😄

**Comment by torifat** [comment]
https://github.com/yarnpkg/yarn/blob/master/src/package-resolver.js#L432-L434

Here, for the attached test case. `dep-b` sets `dep-d` as `ENVIRONMENT_IGNORE` and `this.fetchingPatterns[fetchKey]` to true. So, for `dep-c` it doesn't get updated.

**Comment by kittens** [comment]
Superseded by #2116.

**Pull request closed without merging**
