### PR TITLE
Add flag `--devDependencies` to install dev dependencies only

### PR DESCRIPTION
**Pull request by eyalzek**
This PR aim to support the feature described in this ticket: https://github.com/yarnpkg/yarn/issues/3254, specifically: https://github.com/yarnpkg/yarn/issues/3254#issuecomment-427171762

### CODE REVIEW

**Comment by arcanis** [comment]
While I understand the theory, I don't think it's a good idea. I'm not fond of having flags that install the directory tree in entirely different ways (note it's also true for `--flat` and even `--production` in some degree - this one is a bit more acceptable).

Yarn is all about reproducible builds, and if a flag is needed to get the same output on a machine than on another then it adds a new layer of complexity I'm not comfortable with. Additionally, such a feature seems specific to a single use case, and I prefer for us to avoid that. Features we add should be generic and future-proof, not restricted to a single use case.

**Comment by arcanis** [comment]
While I understand the theory, I don't think it's a good idea. I'm not fond of having flags that install the directory tree in entirely different ways (note it's also true for `--flat` and even `--production` in some degree - this one is a bit more acceptable).

Yarn is all about reproducible builds, and if a flag is needed to get the same output on a machine than on another then it adds a new layer of complexity I'm not comfortable with. Additionally, such a feature seems specific to a single use case, and I prefer for us to avoid that. Features we add should be generic and future-proof, not restricted to a single use case.

**Comment by arcanis** [comment]
While I understand the theory, I don't think it's a good idea. I'm not fond of having flags that install the directory tree in entirely different ways (note it's also true for `--flat` and even `--production` in some degree - this one is a bit more acceptable).

Yarn is all about reproducible builds, and if a flag is needed to get the same output on a machine than on another then it adds a new layer of complexity I'm not comfortable with. Additionally, such a feature seems specific to a single use case, and I prefer for us to avoid that. Features we add should be generic and future-proof, not restricted to a single use case.

**Comment by dreyks** [comment]
this looks like a start of a long discussion similar to ruby's bundler `--only` feature.

the feature is mostly needed for CI flow, e.g. I'm transpiling sources on production machines (heroku) so almost all my dependencies are in `dependencies` group. However there are several really `dev` dependencies - linters, that are to be run only on CI and are not needed in production.

**Comment by deiga** [comment]
@arcanis Like dreyks already commented, this flag is really useful for CI and when using multi-stage builds in Docker.

**Comment by daern91** [comment]
Any more thoughts on this one, @arcanis? Would love to use this in our CI env.

**Comment by bishtawi** [comment]
Any update on this? I would like to see this functionality. I would use it in my CI tests.

**Comment by rebornix** [comment]
This feature is particularly useful for CI pipeline and sometimes for CD as well, especially for monorepos. For example we ship Monaco Editor from VS Code's source code and Monaco Editor has zero dependencies, but we need some shared dev dependences to run tests and builds. In a CI/CD environment, we'd like to install update-to-date dev dependencies only to ensure the pipeline is always fast enough. Currently it's simply not possible.

> Yarn is all about reproducible builds, and if a flag is needed to get the same output on a machine than on another then it adds a new layer of complexity I'm not comfortable with

It doesn't necessarily add another layer, as long as `--production` exits. `--dev` is the counter part of `--production`. Also note that due to the existence of `--production`/`--flat`/`--ignore-optional` (not sure if there are more), flags are need to get the same output on a machine at this moment.

**Comment by MohamadKh75** [comment]
Any updates? 🤔

**Comment by arcanis** [comment]
Yarn 1 is frozen for features, and this won't be merged (sorry @eyalzek :(). Even in the new trunk I'd probably decline for the same reason as stated before: it's difficult enough to understand the rules that govern how dependencies are installed, the less flags we have the better I feel *for the Yarn core*.

With that being said, Yarn now supports plugins (starting from the 2.x line), and it would be trivial for someone to create a contrib plugin implementing this behavior, but without our team having to maintain it. I'd recommend this approach if that's really what you want.

In the meantime I'll close this PR.

**Comment by redaxmedia** [comment]
There is a solution for those who need devDependencies only:

```
npx handpick --target=devDependencies --manager=yarn
```

**Pull request closed without merging**
