### PR TITLE
`yarn upgrade` any dependencies via protocol

### PR DESCRIPTION
**Pull request by juanca**
**Summary**

Whenever a dev dependency is not in a registry but is hosted elsewhere, upgrading the package throws an error. 

e.g. If a package is hosted on a private github repository, it can be installed via `yarn add git-url#sha --dev`. The package is resolved correctly and set as a dependency (with a name). Attempting to `yarn upgrade <package name>` throws an error indicating a missing package in the registries. 

[This also mirrors `yarn upgrade <package name>` behavior for regular dependencies.](https://github.com/yarnpkg/yarn/pull/2780)

**Test plan**

[See initial commit for failing test.](https://github.com/juanca/yarn/commit/0e5631e9f1c381bb2d8d10021bf12ed0c240d6cc)

### CODE REVIEW

**Comment by juanca** [comment]
Looks like this should be standardized across:

- `dependencies`
- `devDependencies`
- `optionalDependencies`
- `peerDependencies`

I can make a test for each with multiple packages (essential the same test over and over again). 

Aye or nay?

**Comment by bestander** [comment]
Aye

**Comment by juanca** [comment]
Done and done.

Looks like CI is having asynchronous intermittent issues. *sigh* 

I'll see if it happens again and perhaps look a bit into it.

**Comment by juanca** [comment]
@bestander Would appreciate a review before this gets too stale. :D

**Comment by juanca** [comment]
Would appreciate a review from a core member.

**Comment by bestander** [comment]
Sorry for a delay, looking at this now

**Comment by wprater** [comment]
Any hope for a release on this?  Im being affected by some GitHub related dependencies that have no version.

**Comment by bestander** [comment]
It is in 0.23

**Comment by wprater** [comment]
ok, looks like I've still got an issue then. I'll try to get something
written up.

**Comment by bestander** [comment]
Thanks for reporting, open a new issue with repro steps

**Pull request merged**
