### PR TITLE
Add an option to not commit to git. Fixes #1228

### LINKED ISSUE #1228: "yarn version" should have an option to not commit to Git
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`yarn version --new-version 1.2.3` always commits to Git. There's an ugly workaround: You can set the `YARN_VERSION_GIT_TAG` environment variable to an empty string:
```
YARN_VERSION_GIT_TAG='' yarn version --new-version 1.2.3
```

This is because [version.js](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/version.js#L110) uses `Boolean(config.getOption('version-git-tag'))`, and [base-registry.js](https://github.com/yarnpkg/yarn/blob/master/src/registries/base-registry.js#L92) populates overrides for these config options from the environment variables. Since it uses the `Boolean` function and all environment variables are strings, the only value that works to disable it is an empty string.

**What is the expected behavior?**
A `--no-commit` or `--no-git-tag-version` flag: Something like `yarn version --new-version 1.2.3 --no-commit` should update the version number without committing it. [npm calls this --no-git-tag-version](https://docs.npmjs.com/cli/version).

### PR DESCRIPTION
**Pull request by karanjthakkar**
**Summary**

Fixes #1228 

**Test plan**

1. Committing without the `--no-git-tag-version` flag does not commit to github
screen shot 2016-10-19 at 4 30 07 pm

2. Committing with the `--no-git-tag-version` flag commits to github
screen shot 2016-10-19 at 4 30 23 pm

### CODE REVIEW

**Comment by Daniel15** [comment]
There's already a config flag that toggles this (`Boolean(config.getOption('version-git-tag'))`), maybe combine it with your new option - For example:
```
if (!flags.gitTagVersion || !Boolean(config.getOption('version-git-tag'))) {
  // Don't tag the version in Git
}
```

Maybe you could return early from the async function itself, rather than returning a dummy function that returns an empty promise?

**Comment by karanjthakkar** [comment]
@Daniel15 Just made some changes. Is that what you were expecting? Or should I just change

`if (isGit && Boolean(config.getOption('version-git-tag'))` to:

`if (isGit && Boolean(config.getOption('version-git-tag')) && flags.gitTagVersion)`

?

**Comment by karanjthakkar** [comment]
There seem to be multiple ways to skip the committing stage so I was wondering which one is right. But I guess in my current implementation the `postVersion` lifecycle script won't be called 🤔

**Comment by karanjthakkar** [comment]
@Daniel15 Bump! Waiting on you to finalise the impl. :)

**Comment by Daniel15** [comment]
Looks good to me!

**Comment by Daniel15** [comment]
Looks good to me! I'd like someone with more experience with the Yarn codebase (like @sebmck) to take a look too 😄

**Comment by bestander** [comment]
I think this is more useful than the config option, let's merge it

**Pull request merged**
