### PR TITLE
Cleaned up mixed quotes and non-quotes for keys in exported object

### PR DESCRIPTION
**Pull request by lirantal**
**Summary**

Currently the exported object uses mixed quotes usage for the keys:
image

Cleaning up the code to use quotes for everything provides a more readable object notation.

### CODE REVIEW

**Comment by lirantal** [comment]
What's with the ember-cli test not resolving properly?

**Comment by bestander** [comment]
Thanks for the PR.
This is a very opinionated improvement, on one hand you get consistency, on the other we will loose more time enforcing it.
I'll close this for now but feel free to vote or discuss whether the project should adopt it.

**Comment by lirantal** [comment]
@bestander it's ok, I totally understand and indeed it was a personal thing that caught my eye and I just had to try a fix for it :-)

Thanks for the feedback!

**Comment by bestander** [comment]
Anyway, welcome to the community and send more!

**Pull request closed without merging**
