### PR TITLE
Fix missing subdeps in production install when those are present in d…

### PR DESCRIPTION
**Pull request by SimenB**
Cherry picked as per https://github.com/yarnpkg/yarn/pull/2921#issuecomment-292515854

### CODE REVIEW

**Comment by SimenB** [comment]
Aww, it fails :(

**Comment by SimenB** [comment]
@bestander master is red, so I won't look into this. Ok?

**Comment by bestander** [comment]
Yeah, we have this instability in CI.
Looks like it is one of the flaky tests failing, should be ok

**Comment by SimenB** [comment]
@bestander Sorry to nag (especially on a weekend), but when can we expect a patch release? 😄

**Comment by bestander** [comment]
Oh, sorry @SimenB, I just got this message lost in my emails.
I'll send the patch now.

**Comment by SimenB** [comment]
0.23.2 is stable so no issue for me 😄

**Pull request merged**
