### PR TITLE
Fix for #686

### PR DESCRIPTION
**Pull request by troydemonbreun**
Fix for #686

### CODE REVIEW

**Comment by troydemonbreun** [comment]
Ah, I see the failed test.  Sorry I didn't check locally - I'm getting errors running tests locally from a clean master build, so I figured I couldn't trust my local tests.  I'll spend time trying to debug local test issues.

**Comment by bestander** [comment]
@troydemonbreun, could you add a test please?
Is this the same as https://github.com/yarnpkg/yarn/pull/934?

**Comment by troydemonbreun** [comment]
Yes,  thanks. Waiting to see where #934 lands.

**Comment by troydemonbreun** [comment]
Replied previously from email, now I see 934 has landed.  I'll close this PR.  Thanks!

**Pull request closed without merging**
