### PR TITLE
Add tests for global command

### PR DESCRIPTION
**Pull request by voxsim**
This pull request adds:
- tests for every global command excluding upgradeInteractive and everyone is side-effect free (I hope)
- move the pre-existent tests under isCI branch because they cause some changes in the prefix or global folder; but If I am wrong please let me know O.o
- Fix https://github.com/yarnpkg/yarn/issues/3162, https://github.com/yarnpkg/yarn/issues/3142, https://github.com/yarnpkg/yarn/issues/3089 (?)
- It closes https://github.com/yarnpkg/yarn/pull/2725 ;)

cc @bestander @arcanis

### CODE REVIEW

**Comment by voxsim** [comment]
IMO we should remove reporter and install from `checkInstalled` function because they were never used. I will try to open another pull-request to see if I am right O.o

**Comment by voxsim** [comment]
@bestander if you don't have time to review this PR right now, I can open a mini PR that fixes for #3142. Right now `yarn global ls` does not work because we pass the flag skipIntegrity instead of skipIntegrityCheck.

**Comment by TimvdLippe** [comment]
I assume this also closes #2725?

**Comment by voxsim** [comment]
@arcanis ok I will look this tomorrow ;)

@TimvdLippe yes it should close that pull request, but please check it, ok?

**Comment by TimvdLippe** [comment]
@voxsim Sure, will do tomorrow 😄

**Comment by voxsim** [comment]
@arcanis now should work ;)

**Comment by voxsim** [comment]
@TimvdLippe done ;)

**Comment by voxsim** [comment]
@TimvdLippe I didn't delete that tests because I have no idea how to prove that tests are useful or not. For what I understand we can delete without worries.

**Comment by arcanis** [comment]
That's great, thanks! Let's merge it! :)

**Pull request merged**
