### PR TITLE
Disable progress bar

### PR DESCRIPTION
**Pull request by olingern**
**Summary**
Per #1956, this enables users to specify a JSON key, **noProgress**, in their _package.json_ to disable the progress bar from showing. 

**Test plan**
Small refactor for testability, created `__tests__/cli/index.js` file and tests for addition.

**Using feature**
Adding the following the `package.json` will disable progress bar output:
`  "noProgress": true,`

### CODE REVIEW

**Comment by torifat** [comment]
IMO, it's better to handle it in `yarn config` than `package,json`. Lets see what others think.

**Comment by torifat** [comment]
@gihrig I wasn't talking about config file in project folder but global config.

**Comment by gihrig** [comment]
@torifat Probly not. I have npm progress bar disabled in global config and never wanted otherwise. So I agree, on second thought, package json makes little sense.

**Comment by olingern** [comment]
@torifat Will refactor this to use `yarn config` unless there are any objections from others :)

**Comment by torifat** [comment]
LGTM cc @bestander

**Pull request merged**
