### PR TITLE
Deleting CONTRIBUTING.md, linking to the website's contributing page instead

### PR DESCRIPTION
**Pull request by chuwik**
**Summary**

Related to #153.
The CONTRIBUTING.md guidelines currently specify the commands to build and test using npm. Probably would make more sense to use 'yarn run' instead, to dogfood our own :)

**Test plan**

Ran the yarn run build/watch/test/lint to verify the work as expected (similar to npm run).

### CODE REVIEW

**Comment by Daniel15** [comment]
I think we should actually totally delete this file, and just use the one on the site: https://yarnpkg.com/en/org/contributing

You can edit the website page here: https://github.com/yarnpkg/website/edit/master/en/org/contributing.md

**Comment by chuwik** [comment]
Makes sense to me @Daniel15! I'll update this PR to remove the CONTRIBUTING.md file and change the link inside README.md to point to the website. I'll send another PR in the other repo for the npm -> yarn change.

**Comment by Daniel15** [comment]
Thank you! I recently deleted the RELEASING file as it was in both this repo and on the site (https://github.com/yarnpkg/yarn/pull/801), so I think it makes sense to do the same thing for this file 😄

**Comment by chuwik** [comment]
@Daniel15 I also removed /RELEASING.md from the .npmignore file since you removed it. No harm in keeping it there, but also probably more explicit to not have it if it doesn't exist (that file can get long pretty easily!).

**Comment by cpojer** [comment]
Thanks for the PR. GitHub uses this file to show a banner when creating an issue or pull request and I believe it is important to keep that. I'm ok linking to the project's contributing file from the website but I prefer keeping it in this repo.

**Comment by Daniel15** [comment]
Ahh, thanks for the info Christoph. Sorry I didn't know about that.

What if we go the opposite way? Delete the page from the site, and keep the
one here? In any case we should only have a single source of truth for this
document.

Sent from my phone.

On Oct 12, 2016 7:20 PM, "Christoph Pojer" <notifications@github.com> wrote:

Thanks for the PR. GitHub uses this file to show a banner when creating an
issue or pull request and I believe it is important to keep that. I'm ok
linking to the project's contributing file from the website but I prefer
keeping it in this repo.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yarnpkg/yarn/pull/939#issuecomment-253395290>, or mute
the thread

**Comment by cpojer** [comment]
Yep, fine with that too. Make it a link to the file in the repo or delete it from the website :)

**Pull request closed without merging**
