### PR TITLE
✎ Remove duplicate 'add' when using global flag

### PR DESCRIPTION
**Pull request by yeskunall**
**Summary**

Just a small typo fix as pointed out by @sarupbanskota as seen when warned to use `add` instead of `install` (using the `global` flag)

Cheers! ❤️

**Test plan**

N/A

### CODE REVIEW

**Comment by bestander** [comment]
Thanks, @yeskunall.
Could you share a bit more context on the fix?

Maybe a screenshot of the output before and after?

**Comment by sarupbanskota** [comment]
@bestander this has to do with https://github.com/yarnpkg/yarn/issues/3620

**Comment by yeskunall** [comment]
Actually @sarupbanskota this simply fixes #3617, and nothing more. I haven't looked at what #3620 is, but this is merely a grammatical fix, nothing more.

I'm currently at work, but @bestander you can expect a screenshot today itself. Sorry for the delay.

**Comment by yeskunall** [comment]
So following from the issue reported in #3617
```
yarn global add add babel-register
```
`yarn` _did_ do the right thing, and the double add only arises due to the fact that it recognises `add` as a package instead of a command.

**Comment by BYK** [comment]
@bestander ping. (feel free to hand this over to me)

**Comment by yeskunall** [comment]
@BYK so my original changes should probably be discarded, but can you maybe shed some light on what @bestander meant in his review?

**Comment by BYK** [comment]
@yeskunall I don't like talking on behalf of people so that's why I pinged him directly. He's in a different time zone so I'm hoping he'd respond when he wakes up :) If not I'll dig in.

**Comment by bestander** [comment]
I think we have an understanding here.

The current change can't be accepted because it breaks error message for `yarn install --global left-pad`, for example because it will say `Run" yarn global left-pad" instead`.

I don't have an opinion how this should be fixed, feel free to use your best judgement and cover different usages of error message.

**Comment by yeskunall** [comment]
I'll look into this! Thanks for the feedback, you guys! ❤️

**Comment by BYK** [comment]
@yeskunall do you need any help from us? I'd love to get this landed before Yarn 1.0! :)

**Comment by bestander** [comment]
Thanks @yeskunall, I think a better solution came from #4040.
Don't feel bad about it, I hope to see more PRs from you here.

**Pull request closed without merging**
