### PR TITLE
yarn publish: respect publishConfig.registry

### PR DESCRIPTION
**Pull request by oligot**
**Summary**

As reported in https://github.com/yarnpkg/yarn/issues/5310, yarn doesn't respect publishConfig in `package.json` when publishing.

This is a first step to use `publishConfig.registry` when publishing.

**Test plan**

Running `yarn publish` with this change respect the `publishConfig.registry` defined in `package.json`

### CODE REVIEW

**Comment by arcanis** [comment]
Thanks!

**Comment by thecodejack** [comment]
any nightly build vresion where I can test this???

**Comment by thecodejack** [comment]
Thanks..found it and it worked..eagerly waiting for **1.5.2**

**Comment by mohr023** [comment]
Just started trying yarn and stumbled upon this... Thanks for the quick fix, looking forward for the release.

**Comment by julianomoreira** [comment]
This fix is not working for me. It's ignoring publishConfig. Is there anything else that needs to be done?

**Comment by dlebedynskyi** [comment]
from what I see 1.6 fixed this issue.

**Comment by thecodejack** [comment]
@mohr023 nop..it is working right away assuming you adding following in your `package.json`

```
"publishConfig": {
    "registry": "http://maven.test.com/nexus/content/repositories/npm-internal/"
  },
```

**Pull request merged**
