### PR TITLE
update eslint, eslint-config-fb-strict and other dependencies

### PR DESCRIPTION
**Pull request by voxsim**
**Summary**
I updated eslint, babel-eslint, eslint-config-fb-strict. This is preopedeutic for prettier.
For now I disabled sort-keys in the eslintrc otherwise we have to change *every* file drastically, maybe it is better to do incrementally.

Some info:
- Now arrow functions with one paramenter don't have parens
- I fixed some tests not catched by the old version of eslint

**Test plan**
Tests already in place

### CODE REVIEW

**Comment by bestander** [comment]
lockfile is not updated

**Comment by bestander** [comment]
Otherwise, great job!
Thank you

**Comment by voxsim** [comment]
Some news:
- downgraded babel-eslint
- removed eslint-config-fbjs because the latest is incompatible with the latest of eslint-config-fb-strict (eslint-config-fb-strict picks an alpha version of eslint-config-fbjs 😱 )
- updated eslint-plugin-flow and eslint-plugin-react

now it seems to work and check the lockfile correctly O.o

@bestander when you have time, let me know if everything is correct

**Comment by voxsim** [comment]
Now prettier works as expected, let me know if you prefer to do dirrent merges or I can push it here ;)

**Comment by bestander** [comment]
Thanks, @voxsim, great work!

**Pull request merged**
